#!/bin/bash
#
# cs_show_memory
#
# (c) 2016 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU General Public License. No warranty.
#
# Version: 2016-07-13 11:20
#

EXE="$0"
#CFG="/etc/ClusterTools2/cs_show_memory"
#test -s $CFG && source $CFG
RDM=$RANDOM
JCTL=""
if test -x $(type -p journalctl); then
	JCTL="/tmp/journalctl.$RDM"
	test -z "${SYSTEM_LOG}" &&\
		SYSTEM_LOG="/var/log/messages"
fi
SYSTEM_LOG="${SYSTEM_LOG} ${JCTL}"
test -z "${ZIPPED_LOG}" &&\
        ZIPPED_LOG="/var/log/messages*bz2"


VM_CONFIG_MEMINFO="
MemTotal:
SwapTotal:
HugePages_Total
CommitLimit:
VmallocTotal:
Hugepagesize:
"

VM_CONFIG_SYSCTL="
vm.dirty_background_bytes
vm.dirty_background_ratio
vm.dirty_bytes
vm.dirty_ratio
vm.pagecache_limit_mb
vm.zone_reclaim_mode
vm.lowmem_reserve_ratio
vm.min_free_kbytes
vm.nr_hugepages
vm.nr_overcommit_hugepages
vm.overcommit_memory
vm.swappiness
kernel.shmmax
kernel.shmall
"

VM_UTILISE_MEMINFO="
Buffers:
Cached:
SwapCached:
Active.anon.:
Inactive.anon.:
Active.file.:
Inactive.file.:
Mlocked:
Dirty:
Shmem:
Slab:
SReclaimable:
Committed_AS:
VmallocUsed:
AnonHugePages:
HardwareCorrupted:
"

VM_UTILISE_MEMINFO_CALC="
MemFree:
Available:
SwapFree:
HugePages_Free:
"

MEMLOG_PATTERN="
Error.DRAM
kernel.*page.allocation.failure
kernel.*segfault.at
Out.of.memory
invoked.oom-killer
pagecache.limit.set
"


function help() {
	echo "usage:	$(basename $0)"
	echo "	$(basename $0) [OPTION]"
	echo
	echo " --help		show help"
	echo " --version	show version"
	echo " --all		show memory configuration and utilisation"
	echo " --configured	show memory configuration"
	echo " --logs		show memory related log messages"
	echo " --utilised	show memory utilisation"
	echo " --workload	estimate memory needed for workload"
	echo
}


function show_configured() {
	# ulimit
	# hugepages, transparent hugepages
	# nfs?
	# tcp bucket, ...?

	# TODO formatting
	echo "### $FUNCNAME"
	echo
	numactl -H | grep -e "^node.*cpus:" -e "^node.*size:"
	echo
	for s in $VM_CONFIG_MEMINFO; do
		grep ^$s /proc/meminfo
	done
	echo
	for s in $VM_CONFIG_SYSCTL; do
		# TODO bash for .->/
		f=$(echo $s | tr "." "/")
		echo -n "$s: "
		cat /proc/sys/$f
	done
	echo
	F="/sys/kernel/mm/transparent_hugepage/enabled"
	echo -n "$F: "
	cat $F
	echo
	# TODO formatting
	F="/proc/cgroups" 
	echo -n "$F: "
	awk '$1=="memory" {print $1,$4}' $F
	echo
	df -h | grep tmpfs
	echo

}


function show_utilised() {
	# ulimit
	# cgroups memory
	# shmem, shmax, shmall
	# tmpfs
	# hugepages, transparent hugepages
	# available (12)
	# ...?

	echo "### $FUNCNAME"
	echo
	numactl -H | grep -e "^node.*free:"
	# TODO numa_used = size - free
	numastat | grep -e "node[0-9]" -e "^numa_miss" | tr -s " "

	echo
	for s in $VM_UTILISE_MEMINFO; do
		grep ^$s /proc/meminfo
	done
	# TODO HugePages_Used = HugePages_Total: - HugePages_Free:
	# TODO Swap_Used = SwapTotal: - SwapFree:
	#
	echo
	df -h | grep tmpfs
	echo
}


function show_logs() {
	echo "### $FUNCNAME"

	echo "logs: $LOG" >/dev/stderr
	which journalctl 2>/dev/null && journalctl --no-pager >$JCTL
	# TODO: more efficient loop
        for e in ${MEMLOG_PATTERN}; do
		echo -n "$e = "
		for f in ${LOG}; do
			test -r $f && cat $f
		done | zgrep -ic $e
	done
	rm $JCTL
}


function show_workload() {
	# Commited_AS + KernelStack + SUnreclaim + Shmem + tmpfs ?

	echo "### $FUNCNAME"
	echo
	echo TODO
}


# main()
case $1 in
	 -v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
	;;
	-c|--configured)
		show_configured
		exit
	;;
	-u|--utilised)
		show_utilised
		exit
	;;
	-w|--workload)
		show_workload
		exit
	;;
	-l|--logs)
		show_logs
		exit
	;;
	-a|--all|*)
		show_configured
		show_utilised
		show_workload
		show_logs
	exit
	;;
esac
#
