#!/bin/bash
#
# cs_show_ensa_status
#
# (c) 2020 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
#
# Version: 2020-11-18 
#

D=$(date +%F_%T)
echo "### $D" "${*}" "###"
crm_mon -1r
echo "==="                      
cs_clusterstate -i | grep -v "###"
echo "==="
ps aux | grep -e ASCS[0-9][0-9] -e ERS[0-9][0-9] | grep -v grep
echo "###"
#
