#!/bin/bash
#
# cs_show_sbd_devices
#
# (c) 2011-2017 SUSE Linux GmbH, Germany.
# (c) 2018-2019 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2019-11-28
#

EXE="$0"

function help() {
	echo "usage: $(basename "$EXE")"
	echo "usage: $(basename "$EXE") OPTION"
	echo
	echo "OPTION:"
	echo " --help           show help."
	echo " --version        show version."
	echo
}


# function main()

case $1 in
	-v|--version)
		echo -n "$(basename "$EXE") "
		head -11 "$EXE" | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
	;;
	*)
		/usr/sbin/cs_make_sbd_devices -d
		exit $?
	;;
esac
#
