#!/bin/bash
#
# cs_wait_for_idle 
#
# (c) 2021 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2021-07-14
#

EXE="$0"
SEC=${2:-5}


function help() {
        echo "usage:    $(basename $0) -s <seconds>"
        echo "usage:    $(basename $0) [ --help | --version ]"
        echo
        echo "OPTION:"
        echo " --help		show help"
        echo " --version	show version info"
	echo " -s <seconds>	loop every <seconds>" 
}


# same as in cs_clusterstate
function get_idle() {
 s_state=$(crmadmin -q -S $(crmadmin -Dq 2>&1 1>/dev/null ) 2>&1 1>/dev/null)
 echo "Cluster state: $s_state"
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
 		exit
	;;
	-s)	# TODO cmdline parsing
		sleep $SEC
		while !( get_idle | grep "Cluster state: S_IDLE" ); do
			sleep $SEC;
		done
	;;
	*)
		help
		exit
	;;
esac
#
