language: bash
sudo: false
script:
  - find ClusterTools2-SLE12 -type f -exec awk ' /^#!.*bash/{print FILENAME} {nextfile}' {} + | grep -v ".*/samples/" | xargs shellcheck -s bash
notifications:
email: true
