.TH ha_related_sap_notes 7 "22 Feb 2022" "" "ClusterTools2"
.\"
.SH NAME
ha_related_sap_notes - selection of SAP notes and knowledge base articles, related to high availability
.\"
.SH DESCRIPTION
This manual page lists SAP notes and knowledge base articles related to high availability topics.

The mentioned documents, and others, are stored with the SAP knowledgebase at
\fBhttps://launchpad.support.sap.com\fP
and
\fBhttps://userapps.support.sap.com/sap/support/knowledge/en/\fP .
.\"
.SH EXAMPLES
.\"
.B * Linux and HA cluster related:
.br
1056161 - SUSE Priority Support for SAP applications
.br
1163337 - Generating core dumps on Linux
.br
1275776 - Linux: Preparing SLES for SAP environments
.br
1310037 - SUSE LINUX Enterprise Server 11: Installation notes
.br
1410736 - TCP/IP: setting keepalive interval
.br
1437105 - Operating system limits for SAP instances
.br
1522993 - Linux: SAP on SUSE KVM - Kernel-based Virtual Machine
.br
1552925 - Linux: High Availability Cluster Solution
.br
1557506 - Linux paging improvements 
.br
1763512 - Support details for SUSE Linux Enterprise for SAP Applications - HA Solution for SAP NetWeaver and SAP S/4HANA
.br
1771258 - Linux: User and system resource limits
.br
1944799 - SAP HANA Guidelines for SLES Operating System Installation
.br
1980196 - Setting Linux Kernel Parameter /proc/sys/vm/max_map_count on SAP HANA Systems
.br
1984787 - SUSE LINUX Enterprise Server 12: Installation notes
.br
2031375 - SAP HANA: Transparent HugePages (THP) setting on Linux
.br
2205917 - SAP HANA DB: Recommended OS settings for SLES 12 / SLES for SAP Applications 12
.br
2284516 - SAP HANA virtualized on SUSE Linux Enterprise Hypervisors
.br
2578899 - SUSE Linux Enterprise Server 15: Installation Note
.br
2684254 - SAP HANA DB: Recommended OS settings for SLES 15 / SLES for SAP Applications 15
.br
3120786 - SAP HANA on SUSE KVM Virtualization with SLES 15 SP2
.br
.\"
.P
.B * SAP on Linux in general:
.br
1301712 - Unix sapstartsrv environment determination
.br
1597355 - Swap-space recommendation for Linux
.br
2308598 - Error "Ifconfig is obsolete" happens when you run startsap to start SAP system
.br
2369910 - SAP Software on Linux: General information
.br
3091152 - sapstartsrv - improved deregistration for UNIX/Linux
.br
3139184 - Linux: systemd integration for sapstartsrv and SAP Hostagent
.br
3145200 - SAP Host Agent 7.22 PL57
.\" TODO 3115048 
.br
405827 - Linux: Recommended file systems
.\"
.P
.B * SAP HANA database related:
.br
1501701 - Single Computing Unit Performance and Sizing
.br
1514967 - SAP HANA: Central Note
.br
1523337 - SAP In-Memory Database 1.0: Central Note
.br
1846872 - "No space left on device" error reported from HANA
.br
1876398 - Network configuration for System Replication in HANA SP6
.br
1888072 - SAP HANA DB: Indexserver crash in strcmp sse42
.br
1890444 - Slow HANA system due to CPU power save mode
.br
1944415 - Hardware Configuration Guide and Software Installation Guide for SUSE Linux Enterprise Server with SAP HANA and SAP Business One
.br
1953429 - SAP HANA and SAP NetWeaver AS ABAP on one Server
.br
1984882 - Using HANA System Replication for Hardware Exchange with minimum/zero Downtime
.br
1999993 - How-To: Interpreting SAP HANA Mini Check Results
.br
1999997 - FAQ: SAP HANA Memory
.br
2000000 - FAQ: SAP HANA Performance Optimization
.br
2021789 - SAP HANA Revison and Maintenance Strategy
.br
2100040 - FAQ: SAP HANA CPU
.br
2131662 - Transparent Huge Pages (THP) on SAP HANA Servers
.br
2196941 - SAP HANA Software Replication Takeover Hook Changes
.br
2235581 - SAP HANA: Supported Operating Systems
.br
2246163 - Indexserver crashes in the onLoad method
.br
2380229 - SAP HANA Platform 2.0 - Central Note
.br
2382421 - How to optimize the network configuration on HANA- and OS-Level
.br
2369981 - Required configuration steps for authentication with HANA System Replication
.br
2399979 - How-To: Configuring automatic SAP HANA Data Collection with SAP HANASitter
.br
2400007 - FAQ: SAP HANA Runtime Dumps
.br
2434562 - System Replication Hanging in Status "SYNCING" or "ERROR" With Status Detail "Missing Log" or "Invalid backup size"
.br
2470289 - FAQ: SAP HANA Non-Uniform Memory Access (NUMA)
.br
2493172 - SAP HANA Hardware and Cloud Measurement Tools
.br
2647673 - HANA Installation Failure
.br
2733483 - Host Auto-Failover Not Occur when Indexserver Crash on Worker Node
.br
2750199 - Incorrect Alert Regarding Unsupported Operating System Version
.br
2779331 - HANA services use large SWAP memory
.br
2800138 - Out of Memory with Allocation Failure Type OPERATING_SYSTEM_LIMIT
.br
2945239 - SAP HANA Platform 2.0 SPS 06 Release Note
.br
3007062 - FAQ: SAP HANA & Third Party Cluster Solutions
.br
3043459 - SAP HANA 2 SPS05 Revision 056.00
.br
3070359 - Python 3 Migration Guide For SAP HANA
.br
3072590 - Python 3 Support for Non-Productive SAP HANA Systems
.br
3084229 - SAP HANA Python Support Scripts Fail due to Incompatibility With Python 3
.br
3093542 - Transition to Python 3 of the Python Distribution Delivered With SAP HANA 2.0 Server
.br
3159746 - Hana 2 Revision 6x crashes on Linux kernel 4.12 or 4.18 on IBM Power platform
.\" TODO 401162
.\"
.P
.B * SAP ASE database related:
.br
2992028 - SYB: Fault Manager: install Fault Manager in separated instance 
.\"
.P
.B * SAP NetWeaver and S/4HANA related:
.br
1153713 - Problems with SAP Management Console (Java)
.\" TODO 1301712
.br
1178686 - Linux: Alternative method to generate a SAP hardware key
.br
146289 - Parameter Recommendations for 64-bit SAP Kernel
.br
1619879 - licensing of HA/DR/cluster - invalid license
.br
1693245 - SAP HA Script Connector Library
.br
174911 - Determining the hardware key (customer key)
.br
1864705 - Compatibility tests for certified HA setups
.br
1872602 - Rolling kernel switch using kernel release limits
.br
2077934 - Rolling kernel switch in HA environments
.br
2254173 - Linux: Rolling Kernel Switch in Pacemaker based NetWeaver HA environments
.br
2464065 - Check of automatic maintenance mode for HA solutions
.br
2501860 - Documentation for SAP NetWeaver Application Server for ABAP 7.52
.br
2625407 - SAP S/4HANA 1809: Release Information Note
.br
2630416 - Support for Standalone Enqueue Server 2
.br
2641019 - Installation of ENSA2 and update from ENSA1 to ENSA2 in SUSE HA environment
.br
2698948 - How to install SAP applications in Failover Cluster without shared disks?
.br
2711036 - Usage of the Standalone Enqueue Server 2 in an HA Environment
.br
2717369 - Download files for installing of SAP S4/HANA 1809, SAP S4/HANA 1909, BW S/4HANA 2.0
.br
2855499 - FAIL: RKS Warning(s): Unsupported SCS instance with additional gateway found
.br
3019275 - ENQU: ENSA 2.0 is blocked by a deadlock
.br
3075829 - New sapstarstrv Web service method "ABAPSetServerInactive"
.br
3115889 - SAP Web Dispatcher embedded deployment in an ASCS/SCS instance
.br
611361 - Hostnames of SAP ABAP Platform servers
.br
768727 - Automatic restart functions in sapstart for processes
.br
927637 - Web service authentication in sapstartsrv as of Release 7.00
.br
941735 - SAP memory management system for 64-bit Linux systems
.br
953653 - Rolling Kernel Switch
.\"
.SH BUGS
Feedback is welcome, please mail to feedback@suse.com
.\"
.SH SEE ALSO
\fBha_related_suse_tids\fR(7), \fBsap_suse_cluster_connector\fR(8), \fBsaptune\fR(8),
.br
https://launchpad.support.sap.com ,
.br
https://documentation.suse.com/sbp/all/ ,
.br
https://documentation.suse.com/sles-sap/
.\"
.SH COPYRIGHT
(c) 2021-2022 SUSE Software Solutions Germany GmbH, Germany.
.br
ClusterTools2 comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
