.TH ha_related_acronyms 7 "04 Nov 2020" "" "ClusterTools2"
.\"
.SH NAME
ha_related_acronyms - selection of acronyms, related to high availability
.\"
.SH DESCRIPTION
This manual page shows acronyms related to high availability topics.
.\"
.SH EXAMPLES

\fBALUA\fP	Asymmetric Logical Unit Access

\fBABI\fP	Application Binary Interface

\fBAPI\fP	Application Programming Interface

\fBASCS\fP	SAP ABAP Central Services Instance 

\fBASM\fP	Oracle Advanced Storage Manager

\fBBIA\fP	Business Impact Analysis

\fBBIOS\fP	Basic Input/Output System

\fBCCM\fP	Consensus Cluster Membership

\fBCIB\fP	Cluster Information Base

\fBCIDB\fP	SAP Central Instance and Database

\fBCFQ\fP	Completely Fair Queueing IO Scheduler

\fBCLVM\fP	Cluster Logical Volume Manager

\fBCMDB\fP	Configuration Management Database

\fBCTDB\fP	Clustered Trivial Database

\fBCRM\fP	Cluster Resource Manager

\fBDB\fP	Database

\fBDC\fP	Designated Coordinator

\fBDCPMM\fP	Intel Data Center Persisten Memory Module

\fBDLM\fP	Distributed Lock Manager 

\fBDM-MPIO\fP	Device Mapper Multipathing	

\fBDR\fP	Disaster Recovery

\fBDRBD\fP	Distributed Replicated Block Device

\fBDVEBMGS\fP	SAP Dialog, Verbucher(Update), Enqueue, Batch, Message, Gateway, Spool

\fBECC\fP	Error Correction Code

\fBERS\fP	SAP Enqeueu Replication Server 

\fBESPOS\fP	Extended Service Pack Overlap Support

\fBEVA\fP	Enterprise Virtual Array

\fBFC\fP	Fibre Channel

\fBGFS2\fP	Global File System 2

\fBGPFS\fP	IBM General Purpose File System

\fBGPL\fP	GNU General Public License

\fBHA\fP	High Availability

\fBHBA\fP	Hostbus Adapter

\fBID\fP	Identifier

\fBIO\fP	Input/Output

\fBI/O\fP	Input/Output

\fBIP\fP	Intelectual Property

\fBIP\fP	Internet Protocol

\fBIPMI\fP	Intelligent Platform Management Interface

\fBITIL\fP	Information Technology Infrastructure Library

\fBLAN\fP	Local Area Network

\fBLPT\fP	Last Primary Timestamp

\fBLUN\fP	Logical Unit Number

\fBLVM\fP	Logical Volume Manager

\fBLRM\fP	Local Resource Manager

\fBLSB\fP	Linux Standard Base

\fBLTSS\fP	Long Term Service Pack Support

\fBLVS\fP	Linux Virtual Server

\fBMAC\fP	Media Access Control 

\fBMDADM\fP	Multiple Disk Administration

\fBMPIO\fP	Multipath Input/Output

\fBMTBF\fP	Mean Time between Failure

\fBMTRR\fP	Mean Time to Repair

\fBMTTF\fP	Mean Time to Failure

\fBNAS\fP	Network Attached Storage

\fBNAT\fP	Network Adress Translation

\fBNFS\fP	Network Filesystem

\fBNIC\fP	Network Interface Card

\fBNOOP\fP	No Operations IO Scheduler

\fBNONE\fP	None Operation IO Scheduler

\fBNVME\fP	Non Volatile Memory Express

\fBOCF\fP	Open Cluster Framework

\fBOCFS2\fP	Oracle Cluster Filesystem 2

\fBOS\fP	Operating System

\fBOSI\fP	Open Systems Interconnection

\fBPAS\fP	SAP Primary Application Server

\fBPE\fP	Policy Engine

\fBPDF\fP	Portable Document Format

\fBPMEM\fP	Persistent Memory

\fBPOST\fP	Power-On Self Test 

\fBPTF\fP	Program Temporary Fix

\fBRA\fP	Reference Architecture

\fBRA\fP	Resource Agent

\fBRAC\fP 	Oracle Real Application Cluster

\fBRAID\fP	Redundant Array of Independent Disks

\fBRAS\fP	Reliability, Availability, Serviceability

\fBRC\fP	Return Code

\fBRCO\fP	Recovery Consistency Objective

\fBRDBMS\fP	Relational Database Management System

\fBRDM\fP	Remote Device Monitoring

\fBREAR\fP	Relax And Recover

\fBRPO\fP	Recovery Point Objective

\fBRTA\fP	Recovery Time Actual	

\fBRTO\fP	Recovery Time Objective

\fBSAN\fP	Storage Area Network

\fBSAR\fP	System Activity Reporter

\fBSAS\fP	Serial Attached SCSI

\fBSBD\fP	STONITH Block Device

\fBSCA\fP	Supportconfig Analysis

\fBSCC\fP	SUSE Customer Center

\fBSCSI\fP	Small Computer System Interface

\fBSFEX\fP	Shared Disk File Exclusiveness

\fBSID\fP	System Identifier

\fBSLA\fP	Service Level Agreement

\fBSLE-HA\fP	SUSE Linux Enterprise High Availability

\fBSLES\fP	SUSE Linux Enterprise Server

\fBSTONITH\fP	Shoot The Other Node Into The Head

\fBSP\fP	Service Pack

\fBSPOF\fP	Single Point Of Failure

\fBSR\fP	Service Request

\fBSR\fP	System Replication

\fBSRDF\fP	EMC Symmetrix Remote Data Facility

\fBSRR\fP	System Replication Role

\fBTE\fP	Transition Engine

\fBTID\fP	Technical Information Document

\fBTLA\fP       Three Letter Acronym

\fBTTL\fP	Time To Live

\fBTUR\fP	Test Unit Ready

\fBUUID\fP	Universally Unique Identifier

\fBVIP\fP	Virtual Internet Protocol Address

\fBWWID\fP	World Wide Identifier
.\"
.SH BUGS
Feedback is welcome, please mail to feedback@suse.com
.\"
.SH SEE ALSO
\fBha_related_suse_tids\fR(7), \fBClusterTools2\fR(7)
.\"
.SH COPYRIGHT
All trademarks are property of their respective owner.
.br
(c) 2015-2018 SUSE Linux GmbH, Germany.
.br
(c) 2019-2020 SUSE Software Solutions Germany GmbH.
.br
ClusterTools2 comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
