#!/bin/bash
#
# grep_error_patterns
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.1-sle10 2011-06-30
#

EXE="$0"

CFG="/etc/ClusterTools/grep_error_patterns"
test -s $CFG && source $CFG

DMSG="/tmp/dmesg.$RANDOM"

test -z "${SYSTEM_LOG}" &&\
	 SYSTEM_LOG="/var/log/messages /var/log/boot.msg /var/log/boot.omsg /var/spool/mail/root /proc/mdstat /proc/net/bonding/bond0"
	 SYSTEM_LOG="${SYSTEM_LOG} ${DMSG}"

test -z "${ZIPPED_LOG}" &&\
	ZIPPED_LOG="/var/log/messages.*bz2"
	ZIPPED_LOG="${ZIPPED_LOG} ${CLUSTER_LOG}.*bz2"

test -z "${ERROR_PATTERN}" &&\
	 ERROR_PATTERN="
"taint.flag"
"no.device.*found"
"lpfc.*err"
"qla.*err"
"qlge.*error"
"NMI.received"
"target.failure"
"reservation.conflict"
"SCSI.*reset"
"LUN.larger"
"I/O.error"
"disabling.*barrier"
"doesn.*support.*DPO.*FUA"
"Unable.*SMART.enabled"
"multi.*path.*down"
"multipathd.*reinstated"
"[Ff]ail.*/dev/md"
"U_\|_U"
"/dev/md.*failed"
"duplicate.VG"
"duplicate.PV"
"not.found"
"dlm.*link.*down"
"ocfs2.*has.evicted"
"ocfs2.*ERR"
"ocfs2.*not.unmounted.cleanly"
"fsck.*recommended"
"EXT.-fs.error"
"iSCSI.connection.*error"
"bond.*link.*down"
"bond.*duplicate.address"
"bond.*not.detect.*failures"
"Link.Failure.Count"
"link.*not.ready"
"link.failure"
"ntpd.*failed"
"ntpd.*time.reset"
"refused.mount.request"
"logrotate.*error"
"Failed.to.read"
"Failed.services.*runlevel"
"
# TODO: pattern for failed module (could not load)
# TODO: async IO from grep kio /proc/slabinof ?
# TODO: verify cluster log msgs. maybe more generic possible ?

test -z "${CLUERR_PATTERN}" &&\
	 CLUERR_PATTERN="
"heartbeat.*lost.packet"
"quorum.lost"
"un-expectedly.down"
"Node.*unclean"
"pengine.*fenced.*resource.failure"
"crm_resource.*Error"
"crmd.*ERROR:"
"crmd.*Updating.failcount.*stop"
"crmd.*Updating.failcount.*start"
"

#"lrmd.*RA.output.*failed"
#"lrmd.*RA.output.*error"
#"Volume.group.*error"
#"LVM.*not.*correctly"
#"CTDB.*not.start"
#"Timeout.*CTDB"
#"not.in.Secondary.mode"
#"demote.*still.primary"
#"Clone.options.misconfigured"
#"eDirectory.*failed.*stop"
#"eDirectory.*not.*configured"
#"eDir.configuration.error"
#"ndsd.*no.*socket"
#"eDirectory.isn.*running"
#"eDirectory.configuration.not"
#"Couldn.*find.device"
#"Couldn.*fsck"
#"Couldn.*mount"
#"DANGER.*NOT.cluster-aware"

function help() {
                echo "usage:	$(basename $0)"
                echo "	$(basename $0) [OPTION]"
                echo
                echo " --help		show help."
                echo " --version	show version."
                echo " --zip		search compressed logs, too."
}


function run_grep() {
	echo "logs: $LOG" >/dev/stderr

	dmesg >$DMSG

        # TODO: more efficient loop
	for e in ${ERROR_PATTERN} ${CLUERR_PATTERN}; do
        	echo -n "$e = "
		for f in ${LOG}; do
			test -r $f && cat $f
		done | zgrep -ic $e
	done

	rm $DMSG
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
        	head -11 $EXE | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
	;;
	-z|--zip)
		LOG="${SYSTEM_LOG}"
		test -s ${CLUSTER_LOG} && LOG="${LOG} ${CLUSTER_LOG}"
		for z in ${ZIPPED_LOG}; do
			test -s $z && LOG="${LOG} ${z}"
		done
		run_grep
		exit
	;;
	*)
		LOG="${SYSTEM_LOG}"
		test -s ${CLUSTER_LOG} && LOG="${LOG} ${CLUSTER_LOG}"
		run_grep
		exit		
	;;
esac
#
