#!/bin/sh
#
# Simple script to reset failcounts
#
# GPL
#

NODES=`cl_status listnodes -n`

CRM_RESOURCE=/usr/sbin/crm_resource
CRM_FAILCOUNT=/usr/sbin/crm_failcount

for node in $NODES
        do
        echo
        echo "Node: $node"
        echo
        for resource in `$CRM_RESOURCE -L | egrep -v "^Resource Group:|^Clone Set:" | awk '{ print $1 }'`
                do
                echo -n "Resource $resource: "
                failcount=`$CRM_FAILCOUNT -G -U $node -r $resource | awk '{ print $2 }' | cut -d= -f2`
                echo $failcount

		case "$failcount" in
			INFINITY | [1-9]* )
			echo -n " -> Failcount greater 0, resetting failcount: "
			$CRM_FAILCOUNT -D -U $node -r $resource
			echo "done"
			;;
		esac


	done

done

