.TH ClusterTools 7 "10 Dec 2009" "" "ClusterTools"
.\"
.SH NAME
ClusterTools \- Tools for setting up and managing heartbeat2 clusters
.\"
.SH DESCRIPTION
The \fBClusterTools\fP package provides tools for setting up and managing heartbeat2 clusters. 
The tools are aimed to make tasks easy around the heartbeat2 cluster manager and the Linux
storage stack.

Main command for managing a running cluster is \fBClusterService\fP. This ASCII-terminal based
menu system allows to perform common administrative tasks. It can be used instead of hb_gui if
no X desktop is available.

Tools like \fBlist_failcounts\fP and \fBcluster_actions\fP help to analyse the cluster behaviour.
A set of tools based on \fBwow\fP allows to make configuration of clusters reproduceable and
efficiant.

Currently the tools are mainly used to setup and manage high-availability cluster for following 
workloads:

- SAP application servers, SAP central instances, SAP database servers

- XEN virtual machine hosts

- Novell eDirectory servers

- Novell ZENworks Linux Management servers

- NFS file servers

- Apache web servers, LAMP servers

- MySQL, PostgreSQL, Oracle database servers
.\"
.SH EXAMPLES
.TP
# wow cc --config edir01.wow 01-A-07-group_add_ndsd
add configuration for a resource of type Novell eDirectory to the cluster. 
Use configuration agent 01-A-07-group_add_ndsd.
Read information about the resource from file edir01.wow .
.TP
# whbcc --config edir01.wow 01-A-07-group_add_ndsd
direct call of whbcc
.TP
# wow sc --all sap_C11.wow >precheck-sap_C11-$HOST
check for allmost all pre-requistes that are needed to set up an HA cluster for SAP instance C11. 
Read information about the needed resources from file sap_C11.wow . Write output into file precheck-sap_C11-<hostname>. 
.TP
# whbsaprecheck --all sap_C11.wow >precheck-sap_C11-$HOST
direct call of whbsaprecheck
.TP
# wow cs
start ASCII-terminal based menu to perform administrative tasks on a running cluster.
.TP
# ClusterService
start ASCII-terminal based menu to perform administrative tasks on a running cluster.
.TP
# wow bk
start cluster configuration backup tool make_hb_backup
.TP
# make_hb_backup
direct call of the tool
.\"
.SH FILES
.TP
/usr/lib/wow/
	wow components in general.
.TP
/usr/lib/wow/agents/
	wow configuration agents for heartbeat2.
.TP
/usr/share/wow/xml/
	wow configuration templates for heartbeat2.
.TP
/usr/share/doc/packages/wow/samples/
	wow config file samples.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
http://ClusterTools.sourceforge.net
.\"
.SH SEE ALSO
\fBwow\fP(8), \fBmake_hb_backup\fP(8), \fBwhbsaprecheck\fP(8), \fBClusterService\fP(8),
\fBlist_failcounts\fP(8), \fBcluster_actions\fP(8), \fBcheck-split-brain\fP(8),
\fBclusterstate\fP(8), \fBlinkstate\fP(8), \fBreset_failcounts\fP(8), \fBshowscores\fP(8)
.\"
.SH AUTHORS
M.Guertler, F.Herschel, L.Pinne
.br
ClusterTools comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
