#!/bin/bash
#
# sapall-clxstack - start all wow agents to configure a clxstack resource group
#
CLXSTACK_ALL_WOW_AGENTS=$(cat <<EOC
01-03-add_ip 
01-04-add_clxeva 
01-05-add_lvm 
01-06-add_fs 
01-07-add_sapdb
01-08-add_sapinst
01-99-add_group-clx
EOC
)

export PATH="$PATH:/usr/lib/ClusterTools2"
WOW_AGENTS_DIR=/usr/lib/ClusterTools2/agents
#
# simple param check
#
if [ $# -ne 1 ]; then
   echo "usage: $0 wow-config-file"
   exit 2
else 
   config=$1
fi
#
#
#
cli_batch=${config%.wow}.sap.cli
echo "creating crm batch file $cli_batch"
#
# create the resulting cli file
#
> $cli_batch
echo "cib new wow" >> $cli_batch
echo "cib use wow" >> $cli_batch
for agent in $CLXSTACK_ALL_WOW_AGENTS
do 
	echo "calling agent $agent" >&2; 
	bash $WOW_AGENTS_DIR/$agent --config $config >> $cli_batch
done 

