#!/bin/bash
#
# ClusterService, cs_service
#
# (c) 2011-2014 SUSE Linux Products GmbH, Germany. Author: F.Herschel
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2014-01-01
# 

cmd=""
case "$1" in
	*)
	cmd="--cmd"
	;;
esac
/usr/sbin/menueng2 --program ClusterService --rscFile /usr/share/ClusterTools2/ClusterService.rsc $cmd "$@"
#
