#!/bin/bash
#
# cs_convert_time
#
# (c) 2016 SUSE Linux GmbH, Germany.
# GNU General Public License. No warranty.
# http://www.gnu.org/licenses/gpl.html
# Author: Ilya Manyugin <imanyugin@suse.com>
#
# Version: 2016-02-16 SLES11
#
# Convert time values between wall time and seconds since Epoch formats.
#

function help(){
	local script_name=$(basename $0)
	echo "${script_name}: convert time values between wall time and seconds since Epoch formats."
	echo
	echo "usage: $script_name time_value"
	echo "usage: $script_name [OPTION]"
	echo
	echo "OPTIONS:"
	echo "--help		show this message"
	echo "--version	print version number and exit"
}

function convert_time(){
	if [[ $# -gt 1 ]]; then
		echo $(date -d "$*" +%s)
	else
		echo $(date -d @$1)
	fi
}

if [[ $# -eq 0 ]]; then
	help
	exit 1
fi

case $1 in
	--version|-v )
			ver_string=$(grep "^# Version:" $0 | cut -c3-)
			echo -e "$(basename $0) $ver_string"
		;;
	--help|-h )
			help
		;;
	* )
		convert_time $@
		;;
esac
#
