#!/bin/bash
#
# cs_dmesg
#
# (c) 2013 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU General Public License. No warranty.
#
# Version: 2015-03-10
#

EXE="$0"


# main()
case $1 in
	-h|--help)	
		echo "usage:	$(basename $0)"
		echo " --help		show help."	
		echo " --version	show version."
		exit
	;;
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	*)
		D=$(date +%s)
		U=$(uptime | tr -d "," |\
			awk '{f=split($3,a,":"); print 60*a[1]+a[2]}')
			# TODO uptime with days
		B=$[ $D - $U ]

		# echo "boot time: $B"
		# TODO convert T (since 1970) from seconds into default format
		# dmesg | awk '{T=$2+'"$B"'; print T,$0}'
		# 
		dmesg | awk '{T=$2+'"$B"'; print T,$0}'
	;;
esac
#
