#!/bin/bash
#
# cs_precheck_for_hana
#
# (c) 2015 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 2015-02-28 19:25
#

EXE="$0"

for CFG in "/etc/ClusterTools2/cs_precheck_for_hana" "/etc/ClusterTools2/cs_show_supportconfig"; do
	test -s $CFG && source $CFG
done

test -z "${TEMP}" &&\
	TEMP="/dev/shm/cltl.$RANDOM"

# TODO use common library with cs_sum_base_config and cs_show_supportconfig

test -z "${HANA_SAP_BOOTARG}" &&\
	HANA_SAP_BOOTARG="
intel_idle.max_cstate=0
processor.max_cstate=0
"
test -z "${HANA_SUSE_BOOTARG}" &&\
	HANA_SUSE_BOOTARG="
elevator=noop
cgroup_disable=memory
"
test -z "${HANA_SAP_SYSCTL}" &&\
	HANA_SAP_SYSCTL="
vm.pagecache_limit_mb
vm.pagecache_limit_ignore_dirty
vm.overcommit_memory
vm.swappiness
vm.max_map_count
kernel.sem
kernel.shmall
kernel.shmmax
net.ipv4.tcp_slow_start_after_idle
"
test -z "${HANA_SUSE_SYSCTL}" &&\
	HANA_SUSE_SYSCTL="
vm.dirty_bytes
vm.dirty_background_bytes
"
# TODO HANA_VERS_MIN as well?
# TODO HANA_SAP_PKG_YES as well?
test -z "${HANA_SAP_SVC_YES}" &&\
	HANA_SAP_SVC_YES="
boot.sysstat
boot.sapinit
boot.clock
ntp
"
test -z "${HANA_SAP_SVC_OFF}" &&\
	HANA_SAP_SVC_OFF="
boot.kdump
"
test -z "${HANA_VERS_MIN}" &&\
	HANA_VERS_MIN="
kernel-default:3.0.101-0.7.15.1
kernel-xen:3.0.101-0.7.15.1
glibc:2.11.3-17.56.2
"
test -z "${HANA_SAP_PKG_YES}" &&\
	HANA_SAP_PKG_YES="
hal
gtk2
iptraf
java-1_6_0-ibm
libicu
mozilla-xulrunner192
ntp
sudo
syslog-ng
tcsh
libssh2-1
libstdc++6
libgcc_s1
expect
autoyast2-installation
yast2-ncurses
bing
bonnie
cairo
findutils-locate
graphviz
iptraf
krb5-32bit
krb5-client
nfs-client
sensors
"
test -z "${HANA_SUSE_PTRN}" &&\
	HANA_SUSE_PTRN="
base
x11
Basis-Devel
sap_hana
ha_sles
"
test -z "${HANA_SUSE_PKG_YES}" &&\
	HANA_SUSE_PKG_YES="
rear
sysstat
supportutils
sapconf
xfsprogs
xfsdump
fio-util
fio-common
fio-sysvinit
libvsl
iomemory-vsl
fio-firmware-ioaccelerator
fio-firmware-highiops
SAPHanaSR
SAPHanaSR-doc
HANA-Firewall
"


function help() {
	echo "usage:	$(basename $0)"
	echo "	$(basename $0) [OPTION]"
	echo
	echo " --help		show help."
	echo " --version	show version."
	echo " --base 	show base config."
	echo " --apps 	show HANA apps config."
	echo
	test $UID -gt 0 && echo "please call as root."
}


function show_base() {
	mkdir $TEMP
	cd $TEMP

	/usr/bin/grep "model.name" /proc/cpuinfo | sort -u
	echo -n "cpu MHz:	"
	/usr/bin/awk '$2=="MHz" {print $4}' /proc/cpuinfo | sort -u | tr "\n" " "
	echo

	/usr/bin/grep -e "MemTotal:" -e "SwapTotal:" -e "VmallocTotal:" /proc/meminfo
	echo
	/usr/bin/zcat /boot/initrd | cpio -itv 2>/dev/null | colrm 43 54 | grep -e dog -e wdt
	echo

	# TODO show recommeded version from HANA_VERS_MIN
	echo -n "Kernel: "; /bin/uname -s -r -v -m -p -i -o
	echo	
	
	# TODO loop
	echo -n "Elevator: deadline: "
	find /sys/devices/ -name "scheduler" -exec grep "\[deadline\]" {} \; | wc -l
	echo -n "Elevator: noop: "
	find /sys/devices/ -name "scheduler" -exec grep "\[noop\]" {} \; | wc -l
	echo -n "Elevator: cfq (=0): "
	find /sys/devices/ -name "scheduler" -exec grep "\[cfq\]" {} \; | wc -l
	echo

	a="bond"
	FOUND=$(ip -o a s | grep $a)
	test -z "${FOUND}" && FOUND="NA"
	echo "network ${a} :      ${FOUND}"
	# TODO look for 10gbit/s 
	echo

	FIL="/boot/grub/menu.lst /etc/sysconfig/bootloader /proc/cmdline"
	for f in $FIL; do
		for a in ${HANA_SAP_BOOTARG} ${HANA_SUSE_BOOTARG}; do
			FOUND=$(grep $a $f)
			test -z "${FOUND}" && FOUND="NA"
			echo "${f}: ${a} :	${FOUND}"
		done
	done
	echo

	OPT="/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor /sys/kernel/mm/transparent_hugepage/enabled /sys/.*/scheduler"
	f="/etc/init.d/boot.local"
	for a in $OPT ; do
		FOUND=$(grep $a $f)
		test -z "${FOUND}" && FOUND="NA"
		echo "${f}: ${a} :      ${FOUND}"
	done
	echo
	f="/sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
	FOUND=$(cat $f 2>/dev/null)
	test -z "${FOUND}" && FOUND="NA"
	echo "$f (=0):	${FOUND}"
	f="/sys/devices/system/cpu/cpuidle/current_driver"
	FOUND=$(cat $f 2>/dev/null)
	test -z "${FOUND}" && FOUND="NA"
	echo "$f (acpi_idle):  ${FOUND}"
	echo

	f=/etc/sysctl.conf
	for a in ${HANA_SAP_SYSCTL} ${HANA_SUSE_SYSCTL}; do
		FOUND=$(grep $a $f)
		test -z "${FOUND}" && FOUND="NA"
		echo "${f}: ${a} :	${FOUND}"
	done
	echo

	# TODO variable
	for f in bootloader kernel kdump; do
		g="/etc/sysconfig/$f"
		echo "${g}:"
		grep -v "^#" $g | tr -s "\n"
		echo 
	done	

	for a in ${HANA_SAP_SVC_YES} ${HANA_SUSE_SVC_YES}; do
		FOUND=$(chkconfig -A | grep $a | awk '{print $2}')
		test -z "${FOUND}" && FOUND="NA"
		echo "chkconfig ${a} ON:	${FOUND}"
	done
	for a in ${HANA_SAP_SVC_OFF} ${HANA_SUSE_SVC_OFF}; do
		FOUND=$(chkconfig -A | grep $a | awk '{print $2}')
		test -z "${FOUND}" && FOUND="NA"
		echo "chkconfig ${a} OFF:	${FOUND}"
	done
	echo

	INSTALLED_PTRN=$(zypper se -t pattern | awk '$1=="i" {print $3}')
	for a in ${HANA_SUSE_PTRN}; do
		FOUND=$(echo $INSTALLED_PTRN | tr " " "\n" | grep $a)
		test -z "${FOUND}" && FOUND="NA"
		echo "pattern ${a}:       ${FOUND}"
	done
	echo

	RPMLIST=$(rpm -qa | sort)
	for a in ${HANA_SAP_PKG_YES} ${HANA_SUSE_PKG_YES}; do
		FOUND=$(echo $RPMLIST | tr " " "\n" | grep $a | tr "\n" " ")
		test -z "${FOUND}" && FOUND="NA"
		echo "${a} :      ${FOUND}"
	done
	# TODO also glibc HANA_VERS_MIN
	echo

	cd $OLDPWD
	rm -rf $TEMP
}


function show_apps() {
	mkdir $TEMP
	cd $TEMP
	# TODO check for SAP programs needed by SAPHanaSR
	# TODO check for disk space for HANA
	# TODO see HWCCT output for other interesting points
	echo

	cd $OLDPWD
	rm -rf $TEMP

}

# main()
case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
        	head -11 $EXE | grep "^# Version: "
		exit
	;;
	-b|--base)
		test $UID -gt 0 && echo "please call as root." && exit
		show_base
		exit
	;;
	-a|--apps)
		test $UID -gt 0 && echo "please call as root." && exit
		show_apps
		exit
	;;
	*)
		help
		exit		
	;;
esac
#
