#!/bin/bash
#
# cs_stresscib
#
# (c) 2015 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU General Public License. No warranty.
#
# Version: 2015-03-03
#

EXE="$0"
ERR="/dev/null"

CFG="/etc/ClusterTools2/cs_stresscib"
test -s $CFG && source $CFG



function help() {
	echo "usage: $(basename $0) [OPTION]"
	echo
	echo " --init		initialise cib stress job."
	echo " --exit		stop cib stress job."
	#echo " --show		show cib stress log."
	echo " --help		show help."
	echo " --version	show version."
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-i|--init)
		# TODO 2nd arg for stress profile (hana ...)
		ln -s /usr/share/ClusterTools2/cs_stresscib.cron /etc/crontab.d/cs_stresscib
		grep -v "^#" /etc/crontab.d/cs_stresscib
		exit
	;;
	-e|exit)

	;;
	-s|show)

	;;
	*)
		help
		exit
	;;
esac
#
