#!/bin/bash
#
# ClusterService, cs_service
#
# (c) 2011-2016 SUSE Linux GmbH, Germany. Author: F.Herschel
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2016-08-03
#

cmd=""
case "$1" in
	*)
	cmd="--cmd"
	;;
esac
/usr/sbin/menueng2 --program ClusterService --rscFile /usr/share/ClusterTools2/ClusterService.rsc $cmd "$@"
#
