#!/bin/bash
#
# cs_show_dmesg
#
# (c) 2013 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU General Public License. No warranty.
#
# Version: 2015-03-10
#
#set -x

EXE="$0"

D=$(date +%s)
U=$(uptime |tr -d ","| awk '{f=split($3,a,":"); print 60*a[1]+a[2]}')
B=$[ $D - $U ]

# TODO 1. add this $B to each time stamp in dmesg output
# TODO 2. convert dmesg output to wall clock time


# main()
case $1 in
	-h|--help)	
	echo "usage:	$(basename $0)"
	echo " --help		show help."	
	echo " --version	show version."
	exit
	;;
	-v|--version)
	echo -n "$(basename $EXE) "
	head -11 $EXE | grep "^# Version: "
	exit
	;;
	*)

		echo "boot time: $B"
#		dmesg | awk '{T=$2+'"$B"';  print T,$0}'
	;;
esac
#
