#!/bin/bash
#
# wow
#
# (c) 2011-2014 SUSE Linux Products GmbH, Germany 
# Author: F.Herschel
# GNU General Public License. No warranty.

cmd=""
case "$1" in
	*)
	cmd="--cmd"
	;;
esac
/usr/sbin/menueng2 --program wow --rscFile /usr/share/ClusterTools2/Wow.rsc $cmd "$@"
#
