#!/bin/bash
# xmstat
#
# Copyright (c) 2008-2011 SUSE Linux GmbH, Germany.
# GNU General Public License - No warranty. 
#
LOG=${1:-/var/log/xmstat.log}
WAIT=${2:-3}

DTIM=$(date +"%F %T")
TIME=${DTIM:11}
DATE=${DTIM:0:10}

HOST=${HOSTNAME:-$(hostname)}

/usr/sbin/xentop -b -d $WAIT -i 2 |\
/usr/bin/awk 'BEGIN{got_dom0=0; date="'$DATE'"; time="'$TIME'"; host="'$HOST'"}\
	{	if ( $1 == "Domain-0" ) ++got_dom0;
		if ( got_dom0 >= 2 )
		{ gsub( "no limit", "no_limit" )
	  	  print host,date,time":",$0 }
	}' >>$LOG
#
