.TH ClusterService 8 "10 Oct 2010" "" "ClusterTools2"
.\"
.SH NAME
ClusterService \- managing pacemaker high-availability cluster
.\"
.SH SYNOPSIS
.B ClusterService
[\fIOPTIONS\fR] [\fIPARAMETER\fR]
.\"
.SH DESCRIPTION
Main command for managing a running cluster is \fBClusterService\fP.
This ASCII-terminal based menu system allows to perform common administrative
tasks. It can be used instead of hb_gui if no X desktop is available.
The program is a frontend to a set of tools.
.\"
.\" .SH OPTIONS
.\"
.SH EXIT STATUS
.B 0
	Successful program execution.
.br
.B >0 
	Usage, syntax or execution errors.
.\"
.\" .SH EXAMPLES
.\"
.SH FILES
.TP
/usr/sbin/ClusterService
	the program itself.
.TP
/usr/share/ClusterTools2/ClusterService.rsc
	default ClusterService resource file.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
http://ClusterTools.sourceforge.net
.\"
.SH SEE ALSO
\fBwow\fP(8), 
.br
http://www.novell.com/partners/sap/sap_on_hasi.pdf
.\"
.SH AUTHORS
Fabian Herschel
.\"
.SH COPYRIGHT
(c) 2009-2010 Fabian Herschel, Germany.
.br
ClusterService comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
