'\" t
.\"     Title: crm_attribute
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/22/2011
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CRM_ATTRIBUTE" "8" "02/22/2011" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
crm_attribute \- manipulate attributes in the CIB
.SH "SYNOPSIS"
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB[options]\fR
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.PP
The
\fBcrm_attribute\fR
command queries and manipulates node attributes and cluster configuration options that are used in the CIB\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR, \fB\-?\fR
.RS 4
Print a help message\&.
.RE
.PP
\fB\-\-verbose\fR, \fB\-V\fR
.RS 4
Turn on debug information\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Increase the level of verbosity by providing additional instances\&.
.sp .5v
.RE
.RE
.PP
\fB\-\-quiet\fR, \fB\-Q\fR
.RS 4
When doing an attribute query using
\fB\-G\fR, print just the value to stdout\&. Use this option with
\fB\-G\fR\&.
.RE
.PP
\fB\-\-get\-value\fR, \fB\-G\fR
.RS 4
Retrieve rather than set the preference\&.
.RE
.PP
\fB\-\-delete\-attr\fR, \fB\-D\fR
.RS 4
Delete rather than set the attribute\&.
.RE
.PP
\fB\-\-attr\-value \fR\fB\fIstring\fR\fR, \fB\-v \fR\fB\fIstring\fR\fR
.RS 4
Value to set\&. This is ignored when used with
\fB\-G\fR\&.
.RE
.PP
\fB\-\-node\-uuid \fR\fB\fInode_uuid\fR\fR, \fB\-u \fR\fB\fInode_uuid\fR\fR
.RS 4
Specify the UUID of the node to change\&.
.RE
.PP
\fB\-\-node\-uname \fR\fB\fInode_uname\fR\fR, \fB\-U \fR\fB\fInode_uname\fR\fR
.RS 4
Specify the uname of the node to change\&.
.RE
.PP
\fB\-\-set\-name \fR\fB\fIstring\fR\fR, \fB\-s \fR\fB\fIstring\fR\fR
.RS 4
Specify the set of attributes in which to read or write the attribute\&.
.RE
.PP
\fB\-\-attr\-name \fR\fB\fIstring\fR\fR, \fB\-n \fR\fB\fIstring\fR\fR
.RS 4
Specify the attribute to set or query\&.
.RE
.PP
\fB\-\-type \fR\fB\fIstring\fR\fR, \fB\-t \fR\fB\fItype\fR\fR
.RS 4
Determine to which section of the CIB the attribute should be set or to which section of the CIB the attribute that is queried belongs Possible values are
\fBnodes\fR,
\fBstatus\fR, or
\fBcrm_config\fR\&.
.sp
Additional Options:
.TS
allbox tab(:);
lB lB.
T{
Type
T}:T{
Additional Options
T}
.T&
l l
l l
l l.
T{
\fBnodes\fR
T}:T{
\fB\-(U|u) \-n [\-s]\fR
T}
T{
\fBstatus\fR
T}:T{
\fB\-(U|u) \-n [\-s]\fR
T}
T{
\fBcrm_config\fR
T}:T{
\fB\-n [\-s]\fR
T}
.TE
.sp 1
.RE
.SH "EXAMPLES"
.PP
Query the value of the \fBlocation\fR attribute in the \fBnodes\fR section for the host \fImyhost\fR in the CIB:
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB\-G\fR \fB\-t\fR nodes \fB\-U\fR \fImyhost\fR \fB\-n\fR location
.fi
.if n \{\
.RE
.\}
.RE
.PP
Query the value of the \fBcluster\-delay\fR attribute in the \fBcrm_config\fR section in the CIB:
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB\-G\fR \fB\-t\fR crm_config \fB\-n\fR cluster\-delay
.fi
.if n \{\
.RE
.\}
.RE
.PP
Query the value of the \fBcluster\-delay\fR attribute in the \fBcrm_config\fR section in the CIB\&. Print just the value:
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB\-G\fR \fB\-Q\fR \fB\-t\fR crm_config \fB\-n\fR cluster\-delay
.fi
.if n \{\
.RE
.\}
.RE
.PP
Delete the \fBlocation\fR attribute for the host \fImyhost\fR from the \fBnodes\fR section of the CIB:
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB\-D\fR \fB\-t\fR nodes \fB\-U\fR \fImyhost\fR \fB\-n\fR location
.fi
.if n \{\
.RE
.\}
.RE
.PP
Add a new attribute called \fBlocation\fR with the value of \fBoffice\fR to the \fIset\fR subsection of the \fBnodes\fR section in the CIB (settings applied to the host \fImyhost\fR):
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB\-t\fR nodes \fB\-U\fR \fImyhost\fR \fB\-s\fR \fIset\fR \fB\-n\fR location \fB\-v\fR office
.fi
.if n \{\
.RE
.\}
.RE
.PP
Change the value of the \fBlocation\fR attribute in the \fBnodes\fR section for the \fImyhost\fR host:
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
\fBcrm_attribute\fR \fB\-t\fR nodes \fB\-U\fR \fImyhost\fR \fB\-n\fR location \fB\-v\fR backoffice
.fi
.if n \{\
.RE
.\}
.RE
.SH "FILES"
.PP

/var/lib/heartbeat/crm/cib\&.xml\(emthe CIB (minus status section) on disk\&. Editing this file directly is strongly discouraged\&.
.SH "SEE ALSO"
.PP
???
.SH "AUTHOR"
.PP
\fBcrm_attribute\fR
was written by Andrew Beekhof\&.
