.TH cs_reset_failcounts 8 "14 Apr 2011" "" "ClusterTools2"
.\"
.SH NAME
cs_reset_failcounts \- reset failcounts for resources in a pacemaker HA cluster 
.\"
.SH SYNOPSIS
.B cs_reset_failcounts \fI[OPTION]\fR
.\"
.SH DESCRIPTION
\fBcs_reset_failcounts\fP TODO
.br
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help.
.HP
\fB --version\fR
	show version.
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/cs_reset_failcounts
	the program itself.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
https://build.opensuse.org/package/show?package=ClusterTools2&project=home%3Afmherschel
.\"
.SH SEE ALSO
\fBClusterTools2\fP(7), \fBcrm_failcount\fP(8), \fBcs_list_failcounts\fP(8)
.\"
.\"
.SH COPYRIGHT
(c) 2009-2012 F.Herschel, Germany.
.br
cs_reset_failcounts comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
