.TH disable_other_watchdog 8 "20 July 2011" "" "ClusterTools2"
.\"
.SH NAME
disable_other_watchdog \- disable other watchdog and reboot-daemons 
.\"
.SH SYNOPSIS
.P
.B disable_other_watchdog
.\"
.SH DESCRIPTION
\fBdisable_other_watchdog\fP 
stop reboot-daemon, disable service, remove watchdog module from running kernel. Write watchdog to modprobe blacklist.
.br
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help.
.HP
\fB --version\fR
	show version.
.HP
\fB --show\fR
	show available watchdog modules and current initrd line.
.\"
.SH EXAMPLES
.br
.TP
* disable watchdog and stop reboot-daemon.
.br
# disable_other_watchdog
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/disable_other_watchdog
	the program itself.
.TP
/etc/ClusterTools2/disable_other_watchdog
	the configuration file.
.TP
/etc/sysconfig/kernel
	the sysconfig kernel section.
.TP
/lib/modules/.../kernel/drivers/watchdog/
	the kernel's watchdog modules.
.\"
.SH BUGS
Currently only HP ASR daemon and few watchdogs are handled. 
Feedback is welcome, please use the project page at
.br
http://ClusterTools.sourceforge.net
.\"
.SH SEE ALSO
\fBmkinitrd\fP(8), \fBSuSEconfig\fP(8), \fBsbd\fP(7),
\fBadd_softdog_to_initrd\fR(8), \fBClusterTools2\fP(7)
.\"
.\"
.SH COPYRIGHT
(c) 2011 L.Pinne, Germany.
.br
disable_other_watchdog comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
