.TH make_sbd_devices 8 "09 July 2011" "" "ClusterTools2"
.\"
.SH NAME
make_sbd_devices \- initilaize SBD devices 
.\"
.SH SYNOPSIS
.P
.B make_sbd_devices \fR[\fI<SBD_OPTS>\fR [\fI<SBD_CONF>\fR]]
.P
.B make_sbd_devices \fIOPTION\fR
.\"
.SH DESCRIPTION
\fBmake_sbd_devices\fP initializes SBD devices defined in the SBD config file.
The first sectors of the devices will be overwritten. This script is simply a
wrapper for the sbd command.
.br
.\"
.SH OPTIONS
.HP
\fB --dump\fR
	show content of SBD devices.
.HP
\fB --help\fR
	show help.
.HP
\fB --version\fR
	show version.
.\"
.SH EXAMPLES
.br
.TP
* Initialize devices as defined in the default SBD config file, using built-in default options.
.br
# make_sbd_devices 
.TP
* Initialize devices with specific options, take other settings from SBD config file. 
.br
# make_sbd_devices "-1 30 -4 130" /etc/sysconfig/sbd
.TP
* Show content of SBD devices.
.br
# make_sbd_devices --dump
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/make_sbd_devices
	the program itself.
.TP
/etc/ClusterTools2/make_sbd_devices
	the program's configuration.
.TP
/etc/sysconfig/sbd
	the SBD configuration.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
http://ClusterTools.sourceforge.net
.\"
.SH SEE ALSO
\fBsbd\fP(7), \fBsbd\fP(8), \fBstonith\fP(8), \fBClusterTools2\fP(7)
.\"
.\"
.SH COPYRIGHT
(c) 2011 L.Pinne, Germany.
.br
make_sbd_devices comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
