'\" t
.\"     Title: Policy Engine
.\"    Author: Andrew Beekhof <andrew@beekhof.net>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/22/2011
.\"    Manual: Pacemaker Configuration
.\"    Source: Pacemaker Configuration
.\"  Language: English
.\"
.TH "POLICY ENGINE" "8" "02/22/2011" "Pacemaker Configuration" "Pacemaker Configuration"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pengine \- Policy Engine Options
.SH "SYNOPSIS"
.PP
[\fBno\-quorum\-policy\fR=enum] [\fBsymmetric\-cluster\fR=boolean] [\fBdefault\-resource\-stickiness\fR=integer] [\fBis\-managed\-default\fR=boolean] [\fBmaintenance\-mode\fR=boolean] [\fBstart\-failure\-is\-fatal\fR=boolean] [\fBenable\-startup\-probes\fR=boolean] [\fBstonith\-enabled\fR=boolean] [\fBstonith\-action\fR=enum] [\fBstonith\-timeout\fR=time] [\fBstartup\-fencing\fR=boolean] [\fBcluster\-delay\fR=time] [\fBbatch\-limit\fR=integer] [\fBdefault\-action\-timeout\fR=time] [\fBstop\-all\-resources\fR=boolean] [\fBstop\-orphan\-resources\fR=boolean] [\fBstop\-orphan\-actions\fR=boolean] [\fBremove\-after\-stop\fR=boolean] [\fBpe\-error\-series\-max\fR=integer] [\fBpe\-warn\-series\-max\fR=integer] [\fBpe\-input\-series\-max\fR=integer] [\fBnode\-health\-strategy\fR=enum] [\fBnode\-health\-green\fR=integer] [\fBnode\-health\-yellow\fR=integer] [\fBnode\-health\-red\fR=integer] [\fBplacement\-strategy\fR=enum]
.SH "DESCRIPTION"
.PP
This is a fake resource that details the options that can be configured for the Policy Engine\&.
.SH "SUPPORTED PARAMETERS"
.PP
\fBno\-quorum\-policy\fR = enum [stop]
.RS 4
What to do when the cluster does not have quorum
.sp
What to do when the cluster does not have quorum Allowed values: stop, freeze, ignore, suicide
.RE
.PP
\fBsymmetric\-cluster\fR = boolean [true]
.RS 4
All resources can run anywhere by default
.RE
.PP
\fBdefault\-resource\-stickiness\fR = integer [0]
.RS 4
.sp
.RE
.PP
\fBis\-managed\-default\fR = boolean [true]
.RS 4
Should the cluster start/stop resources as required
.RE
.PP
\fBmaintenance\-mode\fR = boolean [false]
.RS 4
Should the cluster monitor resources and start/stop them as required
.RE
.PP
\fBstart\-failure\-is\-fatal\fR = boolean [true]
.RS 4
Always treat start failures as fatal
.sp
This was the old default\&. However when set to FALSE, the cluster will instead use the resource\'s failcount and value for resource\-failure\-stickiness
.RE
.PP
\fBenable\-startup\-probes\fR = boolean [true]
.RS 4
Should the cluster check for active resources during startup
.RE
.PP
\fBstonith\-enabled\fR = boolean [true]
.RS 4
Failed nodes are STONITH\'d
.RE
.PP
\fBstonith\-action\fR = enum [reboot]
.RS 4
Action to send to STONITH device
.sp
Action to send to STONITH device Allowed values: reboot, poweroff
.RE
.PP
\fBstonith\-timeout\fR = time [60s]
.RS 4
How long to wait for the STONITH action to complete
.RE
.PP
\fBstartup\-fencing\fR = boolean [true]
.RS 4
STONITH unseen nodes
.sp
Advanced Use Only! Not using the default is very unsafe!
.RE
.PP
\fBcluster\-delay\fR = time [60s]
.RS 4
Round trip delay over the network (excluding action execution)
.sp
The "correct" value will depend on the speed and load of your network and cluster nodes\&.
.RE
.PP
\fBbatch\-limit\fR = integer [30]
.RS 4
The number of jobs that the TE is allowed to execute in parallel
.sp
The "correct" value will depend on the speed and load of your network and cluster nodes\&.
.RE
.PP
\fBdefault\-action\-timeout\fR = time [20s]
.RS 4
How long to wait for actions to complete
.RE
.PP
\fBstop\-all\-resources\fR = boolean [false]
.RS 4
Should the cluster stop all active resources (except those needed for fencing)
.RE
.PP
\fBstop\-orphan\-resources\fR = boolean [true]
.RS 4
Should deleted resources be stopped
.RE
.PP
\fBstop\-orphan\-actions\fR = boolean [true]
.RS 4
Should deleted actions be cancelled
.RE
.PP
\fBremove\-after\-stop\fR = boolean [false]
.RS 4
Remove resources from the LRM after they are stopped
.sp
Always set this to false\&. Other values are, at best, poorly tested and potentially dangerous\&.
.RE
.PP
\fBpe\-error\-series\-max\fR = integer [\-1]
.RS 4
The number of PE inputs resulting in ERRORs to save
.sp
Zero to disable, \-1 to store unlimited\&.
.RE
.PP
\fBpe\-warn\-series\-max\fR = integer [\-1]
.RS 4
The number of PE inputs resulting in WARNINGs to save
.sp
Zero to disable, \-1 to store unlimited\&.
.RE
.PP
\fBpe\-input\-series\-max\fR = integer [\-1]
.RS 4
The number of other PE inputs to save
.sp
Zero to disable, \-1 to store unlimited\&.
.RE
.PP
\fBnode\-health\-strategy\fR = enum [none]
.RS 4
The strategy combining node attributes to determine overall node health\&.
.sp
Requires external entities to create node attributes (named with the prefix \'#health\') with values: \'red\', \'yellow\' or \'green\'\&. Allowed values: none, migrate\-on\-red, only\-green, progressive, custom
.RE
.PP
\fBnode\-health\-green\fR = integer [0]
.RS 4
The score \'green\' translates to in rsc_location constraints
.sp
Only used when node\-health\-strategy is set to custom or progressive\&.
.RE
.PP
\fBnode\-health\-yellow\fR = integer [0]
.RS 4
The score \'yellow\' translates to in rsc_location constraints
.sp
Only used when node\-health\-strategy is set to custom or progressive\&.
.RE
.PP
\fBnode\-health\-red\fR = integer [\-INFINITY]
.RS 4
The score \'red\' translates to in rsc_location constraints
.sp
Only used when node\-health\-strategy is set to custom or progressive\&.
.RE
.PP
\fBplacement\-strategy\fR = enum [default]
.RS 4
The strategy to determine resource placement
.sp
The strategy to determine resource placement Allowed values: default, utilization, minimal, balanced
.RE
.SH "AUTHOR"
.PP
\fBAndrew Beekhof\fR <\&andrew@beekhof\&.net\&>
.RS 4
Author.
.RE
