.TH sleha_cleanup 8 "27 Jan 2011" "" "ClusterTools2"
.\"
.SH NAME
sleha_cleanup \- remove cluster information base from cluster node
.\"
.SH SYNOPSIS
.B sleha_cleanup
.\"
.SH DESCRIPTION
\fBsleha_cleanup\fP cleans up a pacemaker HA cluster node. 
It removes the cluster information base, the policy engine logs, the ring
status and core files that a cluser node has generated during its operation.
Only the basic cluster configuration in /etc will be left.
.br
Calling this command will shut down the cluster service and all resources on
the node. It also will remove the complete cluster resource configuration and
cluster history. 
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/sleha_cleanup
	the program itself.
.TP
/var/lib/corosync/, /var/lib/heartbeat/cores/, /var/lib/heartbeat/crm/, /var/lib/pengine/
	the directories to be cleaned up.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
http://ClusterTools.sourceforge.net
.\"
.SH SEE ALSO
\fBhb_report\fP(8), \fBmake_hb_backup\fP(8)
.\"
.\"
.SH COPYRIGHT
(c) 2011 L.Pinne, Germany.
.br
sleha_cleanup comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
