#!/bin/bash
#
# add_mod_to_initrd
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: A.Rehg, L.Pinne
# 
# Version: 0.02 2011-08-25 09:45
#

EXE="$0"
MOD=${1:-"softdog"}
FIL="/etc/sysconfig/kernel"
BAK=${FIL}.bak


function help(){
	echo "usage: $(basename $0) [<MODULE>]"
	echo "usage: $(basename $0) [OPTION]"
	echo
	echo "OPTION:"
	echo " --help		show help."
	echo " --version	show version."
	echo " --show 	show available wathdog modules and initrd line."
	echo
}


function version(){
	echo -n "$(basename $EXE) "
	head -11 $EXE | grep "^# Version: "
}


function show_mod(){
	V=$(uname -a | awk '{print $3}')
	OTHMOD=$(ls /lib/modules/${V}/kernel/drivers/watchdog/)

# TODO
#	echo "active watchdog module:"
#	fuser -f /dev/watchdog
#	lsof ?

	echo "loaded watchdog modules:"
	for m in $OTHMOD; do
		lsmod $m 2>/dev/null
	done

	echo "configured watchdog module:"
	grep -v "#.*INITRD_MODULES" $FIL | grep "^INITRD_MODULES=.*$MOD"
	grep -v "#.*MODULES_LOADED_ON_BOOT" $FIL | grep "^MODULES_LOADED_ON_BOOT=.*$MOD"
	
	echo "initrd watchdog module:"
	/bin/zcat /boot/initrd | cpio -itv 2>/dev/null |\
               	grep "lib/modules/*/kernel/drivers/watchdog/.*ko$"

	echo "available watchdog modules:"
	echo $OTHMOD
}


function add_mod(){
	echo "INFO: start $EXE $FUNCNAME"
	test -s $FIL || exit 2
	grep -v "#.*INITRD_MODULES" $FIL | grep "INITRD_MODULES=.*$MOD" >/dev/null
	RC=$?

	if [ $RC -gt 0 ]; then
		cp -a $FIL $BAK || exit $?
		awk -F'"' '     $1=="INITRD_MODULES=" {print $1"\""$2" '"$MOD"'\" "}
        		        $1!="INITRD_MODULES=" {print}' $BAK >$FIL &&
		echo "INFO: wrote $FIL"
		mkinitrd
	else
        	echo "WARN: found \"${MOD}\" already in ${FIL}"
	fi
	echo "INFO: end $EXE $FUNCNAME"
}


function load_mod() {
	echo "INFO: start $EXE $FUNCNAME"
		modprobe $MOD
	echo "INFO: end $EXE $FUNCNAME"
}


# function main()

case $1 in
	-h|--help)
		help
		exit
	;;
	-v|--version)
		version
		exit
	;;
	-s|--show)
		echo "INFO: start $EXE"
		show_mod
		echo "INFO: normal_end $EXE"
		exit
	;;
	*)
		echo "INFO: start $EXE"
		for w in hpwdt ibmasr iTCO_wdt; do
			rmmod $w 2>/dev/null
		done
		add_mod
		load_mod
		echo "INFO: normal_end $EXE"
		exit
	;;
esac
#
