#!/bin/bash
#
# add_mod_to_initrd
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: A.Rehg, L.Pinne
# 
# Version: 0.02 2011-07-20 17:20
#

EXE="$0"
MOD=${1:-"softdog"}
FIL="/etc/sysconfig/kernel"
BAK=${FIL}.bak


function help(){
	echo "usage: $(basename $0) [<MODULE>]"
	echo "usage: $(basename $0) [OPTION]"
	echo
	echo "OPTION:"
	echo " --help		show help."
	echo " --version	show version."
	echo " --show 	show available wathdog modules and initrd line."
	echo
}


function version(){
	echo -n "$(basename $EXE) "
	head -11 $EXE | grep "^# Version: "
}


function add_mod(){
	echo "INFO: start $EXE $FUNCNAME"
	test -s $FIL || exit 2
	grep -v "#.*INITRD_MODULES" $FIL | grep "INITRD_MODULES=.*$MOD" >/dev/null
	RC=$?

	if [ $RC -gt 0 ]; then
		cp -a $FIL $BAK || exit $?
		awk -F'"' '     $1=="INITRD_MODULES=" {print $1"\""$2" '"$MOD"'\" "}
        		        $1!="INITRD_MODULES=" {print}' $BAK >$FIL
		mkinitrd
	else
        	echo "WARN: found \"${MOD}\" already in ${FIL}"
	fi
	echo "INFO: end $EXE $FUNCNAME"
}


function load_mod() {
	echo "INFO: start $EXE $FUNCNAME"
		# V=$(uname -a | awk '{print $3}')
		# TODO MODS=$(/lib/modules/${V}/kernel/drivers/watchdog/ | )
		rmmod hpwdt
		modprobe $MOD
	echo "INFO: end $EXE $FUNCNAME"
}


# function main()

case $1 in
	-h|--help)
		help
		exit
	;;
	-v|--version)
		version
		exit
	;;
	-s|--show)
		# TODO
		# echo "loaded watchdog module:"
		# lsmod list from dirtectory
		echo "configured initrd watchdog module:"
		grep -v "#.*INITRD_MODULES" $FIL | grep "INITRD_MODULES=.*$MOD"	
		echo "available watchdog modules:"
		V=$(uname -a | awk '{print $3}')
		ls /lib/modules/${V}/kernel/drivers/watchdog/
		exit
	;;
	*)
		echo "INFO: start $EXE"
		add_mod
		load_mod	
		echo "INFO: normal_end $EXE"
	;;
esac
#
