#!/bin/bash
#
# clusterstate 
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.1 2011-08-30
#

EXE="$0"

CFG="/etc/ClusterTools2/clusterstate"
test -s $CFG && source $CFG

test -z "${ETH}" &&\
	 ETH="bond0 eth3"
test -z "${SCF}" &&\
	 SCF="/etc/sysconfig/sbd"
test -z "${SBD}" && test -s $SCF &&\
	SBD=$( awk -F"=" '$1=="SBD_DEVICE" {print $2}' $SCF |\
		tr -d "\""|tr ";" "\n" )

HST=$(hostname -f)
DAT=$(date +"%Y-%m-%d %T")


function help() {
	echo "usage:    $(basename $0) [OPTION]"
	echo
	echo " --help           show help."
	echo " --version        show version."
}


function get_state() {
echo "### $HST - $DAT ###"
echo
crm_mon -r1 |\
 awk '$1=="Current"||$1=="Online:"||$1=="OFFLINE:"||$3=="UNCLEAN"{print $0}'
# TODO: efficient awk
echo -n "Stopped/FAILED resources: "
crm_mon -r1 | awk '$3=="Stopped"||$0~/FAILED/{print $0}' | wc -l
echo -n "Started resources: "
crm_mon -r1 | awk '$3=="Started"{print $0}' | wc -l

echo
echo "Ring:"
corosync-cfgtool -s | grep -B1 "status.*=" | grep -v "^--$"

echo
for i in $ETH; do
	ip -o a s $i | awk '$0~/state/{print $2,$3}'
	case $i in
	bond?)
		cat /proc/net/bonding/$i | grep -B1 "MII.Status" | grep -v "^--$"
	 	# TODO ethtool
	;;
	eth?)
		#ethtool $ETH | grep "Link detected:"
	;;
	esac
done

echo
for s in $SBD; do
	echo ${s}
	sbd -d ${s} list
done

# TODO FS

echo
# TODO no grep-grep
cat /proc/mdstat | grep -v "Personalities.:" | grep -v "bitmap.*chunk$" |\
	 tr -s "\n" 
echo
vgs
# TODO FS
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
	;;
	*)
		get_state
		exit
	;;
esac
#
