#!/bin/bash
#
# clusterstate 
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.1 2011-09-02
#

EXE="$0"

CFG="/etc/ClusterTools2/clusterstate"
test -s $CFG && source $CFG

test -z "${ETH}" &&\
	 ETH="bond0 eth3"
test -z "${SCF}" &&\
	 SCF="/etc/sysconfig/sbd"
test -z "${SBD}" && test -s $SCF &&\
	SBD=$( awk -F"=" '$1=="SBD_DEVICE" {print $2}' $SCF |\
		tr -d "\""|tr ";" "\n" )

HST=$(hostname -f)
DAT=$(date +"%Y-%m-%d %T")


function help() {
	echo "usage:    $(basename $0) [OPTION]"
	echo
	echo " --help           show help."
	echo " --version        show version."
}


function get_state() {
echo "### $HST - $DAT ###"
echo
crm_mon -r1 |\
 awk '$1=="Current"||$1=="Online:"||$1=="OFFLINE:"||$3=="UNCLEAN"{print $0}'
# TODO: efficient awk
echo -n "Stopped/FAILED resources: "
crm_mon -r1 | awk '$3=="Stopped"||$0~/FAILED/{print $0}' | wc -l
echo -n "Started resources: "
crm_mon -r1 | awk '$3=="Started"{print $0}' | wc -l

echo
echo "Ring:"
corosync-cfgtool -s | grep -B1 "status.*=" | grep -v "^--$"

echo
for i in $ETH; do
	ip -o a s $i | awk '$0~/state/{print $2,$3}'
	case $i in
	bond?)
		cat /proc/net/bonding/$i | grep -B1 "MII.Status" | grep -v "^--$"
	 	# TODO ethtool
	;;
	eth?)
		#ethtool $ETH | grep "Link detected:"
	;;
	esac
done

echo
for s in $SBD; do
	echo ${s}
	sbd -d ${s} list
done
echo

# TODO check for WWIDs 3600...=SAN/SCSI, 1494...=iSCSI 
# TODO configurable pattern for SAN LUNs (f.e "HP,OPEN-V", "HP,HSV"), local LUNs (f.e. "HP,LOGICAL.VOLUME"), iSCSI LUNs (f.e. "IET,VIRTUAL-DISK")
# TODO call multipath only once and put ouput in variable
# echo -n "total LUNs: "
#	 multipath -l | grep -c "^[0-9].*dm-[0-9]"
echo -n "SCSI LUNs: "
	multipath -l | grep -c "^3600.*dm-"
echo -n "iSCSI LUNs: "
	multipath -l | grep -c "^1494.*dm-"
echo

# TODO no grep-grep
#grep -v "Personalities.:" /proc/mdstat | grep -v "bitmap.*chunk$" | tr -s "\n" 
echo -n "MDs total: "
	grep -c "^md[1-9].*:" /proc/mdstat
echo -n "MDs complete: "
	grep -c "\[UU\]" /proc/mdstat
# TODO MDs syncing / in-sync
#echo -n "MDs syncing: "
#	grep -c <TODO> /proc/mdstat
echo -n "MDs split: "
	grep -c "U_\|_U" /proc/mdstat
echo

vgs
# TODO FS: cat /proc/mount wg. ro-FS
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
	;;
	*)
	# TODO separate functions overview, cluster, network, storage, processes
		get_state
		exit
	;;
esac
#
