#!/bin/bash
#
# cs_check_lsbinit
#
# (c) 2013 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version : 2013-08-07
#

EXE=$0
ERR=/dev/null
# TODO use config file for patterns and number


function check() {
  OK=0; KO=0
  for f in /etc/init.d/* ; do
	RC=0
	if [ -f $f -a -x $f ]; then
		m=$( grep -c -e "^### BEGIN INIT INFO" \
		-e "^# Provides: " \
		-e "^# Default-Start: " \
		-e "^# Default-Stop: " \
		-e "^### END INIT INFO" \
		-e "[[:space:]]\?/etc/rc.status" \
		-e "[[:space:]]\?start\*\?)" \
		-e "[[:space:]]\?stop\*\?)" \
		-e "[[:space:]]\?status\*\?)" \
		$f 2>>$ERR )
		# TODO better regexp for start (see rpmconfigcheck "start|")
		# TODO better regexp for stop,status
		#-e " /etc/init.d/functions" \
		#-e " /lib/lsb/init-functions" \
		# $m should equal to num of grep patterns $LM
		LM=9 
		if [ $m -lt $LM ]; then
			KO=$[ $KO + 1 ]
			echo -n "$f : $m/$LM"
			echo
	 	else	OK=$[ $OK + 1 ]
		fi
	fi
  done

  echo "OK: $OK"
  echo "KO: $KO"
}


function show() {
	f=$1
	# TODO common search function
	# TODO show missing

	echo "=== need:"
	echo "^### BEGIN INIT INFO"
	echo "^# Provides: "
	echo "^# Default-Start: "
	echo "^# Default-Stop: "
	echo "^### END INIT INFO"
	echo "[[:space:]]\?/etc/rc.status"
	echo "[[:space:]]\?start\*\?)"
	echo "[[:space:]]\?stop\*\?)"
	echo "[[:space:]]\?status\*\?)"
	echo "[[:space:]]\?/etc/rc.status"
	echo "==="
	echo "=== found:"
	grep -e "^### BEGIN INIT INFO" \
	-e "^# Provides: " \
	-e "^# Default-Start: " \
	-e "^# Default-Stop: " \
	-e "^### END INIT INFO" \
	-e "[[:space:]]\?/etc/rc.status" \
	-e "[[:space:]]\?start\*\?)" \
	-e "[[:space:]]\?stop\*\?)" \
	-e "[[:space:]]\?status\*\?)" \
	$f 2>>$ERR
	echo "==="
	rpm -qf $f 2>>$ERR
}


function help() {
	echo "$(basename $EXE) --show <script>" 
	echo "$(basename $EXE) --check"
	echo "$(basename $EXE) --version | --help"
	echo "this script is quite beta"
	echo "see also init.d(7), http://refspecs.linux-foundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html"
}


# main()
case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-s|--show)
		test $UID -gt 0 && echo "please call as root." && exit
		show $2
		exit
	;;
	-c|--check)
		test $UID -gt 0 && echo "please call as root." && exit
		check
		exit
	;;
	*)
		help
		exit
	;;
esac
#
