#!/bin/bash
#
# disable_other_watchdog
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: L.Pinne
#
# Version: 0.01 2011-07-21 22:22
#
#set -x

EXE="$0"
TMP="/tmp/cltl.$RANDOM"
FIL="/etc/sysconfig/kernel"
CFG="/etc/ClusterTools2/disable_other_watchdog"
test -s $CFG && source $CFG

test -z "$MODCFG" && MODCFG="/etc/modprobe.d/ClusterTools2"
test -z "$METHOD" && METHOD="hp-asrd"
test -z "$MODULES" && MODULES="hpwdt iTCO_wdt ibmasr"


function help(){
        echo "usage: $(basename $0) OPTION"
        echo "usage: $(basename $0) --stop <METHOD>"
        echo
        echo "OPTION:"
        echo " --help		show help."
        echo " --version	show version."
        echo " --list		list module blacklist and initrd line."
        echo " --stop		disable other restart method."
        echo
}


function disable_hpasr() {
	echo "INFO: start $EXE $FUNCNAME"

	for m in $METHOD; do
		/etc/init.d/$METHOD stop
		chkconfig $METHOD off
	done
	# TODO separate function that checks for loaded modules from /lib/...
	# V=$(uname -a | awk '{print $3}')
	# TODO MODS=$(/lib/modules/${V}/kernel/drivers/watchdog/ | )

	mv $MODCFG $MODCFG.bak
	for m in $MODULES; do
		echo blacklist ${m} >>$MODCFG
	done
	for m in $MODULES; do
		rmmod ${m}
	done

	# TODO: /etc/sysconfig/kernel
	test -s $FIL || exit 2
	# TODO: mkinitrd ?
	echo "INFO: end $EXE $FUNCNAME"
}


function list_other_restart() {

	V=$(uname -a | awk '{print $3}')
	OTHMOD=$(ls /lib/modules/${V}/kernel/drivers/watchdog/)
	echo "available watchdog modules:"
	echo $OTHMOD

	echo "configured initrd watchdog module:"
	grep -v "#.*INITRD_MODULES" $FIL | grep "^INITRD_MODULES="

	echo "loaded watchdog modules:"
	for m in $OTHMOD; do
		lsmod $m 2>/dev/null
	done

	echo "installed reboot daemon:"
	for m in $METHOD; do
		ls /etc/init.d/$METHOD 2>/dev/null
		/etc/init.d/$METHOD status 2>/dev/null
		chkconfig -l $METHOD 2>/dev/null
	done
	
	echo "installed initrds:"
	ls -l /boot/initrd*
}


function guess_other_restart() {
	echo "INFO: start $EXE $FUNCNAME"
	echo noop
	echo "INFO: end $EXE $FUNCNAME"
}


# function main()

case $1 in
        -v|--version)
                echo -n "$(basename $EXE) "
                head -11 $EXE | grep "^# Version: "
                exit
        ;;
        -g|--guess)
                echo "INFO: start $EXE"
                guess_other_restart
                echo "INFO: normal_end $EXE"
		exit
        ;;
	-l|--list)
		echo "INFO: start $EXE"
		list_other_restart
		echo "INFO: normal_end $EXE"
		exit
	;;
	-s|--stop)
		echo "INFO: start $EXE"
		disable_hpasr
		echo "INFO: normal_end $EXE"
		exit
	;;
        *)
                help
                exit
        ;;
esac
#
