#!/bin/bash
#
# elevenmin
#
# Version: 2013-04-04
#
# (c) 2013 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
#
# test if HW clock would be set by boot.clock on shutdown
# function from boot.clock
#

ELEVENMIN_MODE=no

typeset -i STA_CLOCK=$(adjtimex --print | sed -rn '/^[[:blank:]]*status:/{ s/[^[:digit:]]*([[:digit:]]+)/\1/p; }')
test $((STA_CLOCK & 65)) -eq 1 && ELEVENMIN_MODE=yes
echo "if kernel is within 11 minute mode do not adjust HW clock. ELEVENMIN_MODE="$ELEVENMIN_MODE
#

