#!/bin/bash
#
# filefind
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.1 2011-05-18
#

EXE="$0"

CFG="/etc/ClusterTools2/filefind"
test -s $CFG && source $CFG

TMP=/tmp/ff.$RANDOM

#DIRS="/sapmnt /usr/sap /home /oracle"
DIRS="/sapmnt /usr/sap /home /sapdb"
SID1=NA0
SID2=NA9
SADM1=na0adm
SADM2=na9adm
DADM1=sqdna0
DADM2=sqdna9


function help() {
	echo "usage:    $(basename $0)"
	echo "  $(basename $0) [OPTION]"
	echo
	echo " --help           show help."
	echo " --version        show version."
}


function run_filefind {
	for d in $DIRS; do
		find $d -printf %m\\t%g\\t%u\\t%h"/"%f\\n >$SID1.orig.ff
		sed s/$SID1/$SID2/g <$SID1.orig.ff >$TMP.2
		sed s/$SADM1/$SADM2/g <$TMP.2 >$TMP.3
		sed s/$DADM1/$DADM2/g <$TMP.3 >$SID2.fake.ff
	done
	rm $TMP.?
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
		;;
	*)
		run_filefind
		exit            
		;;
esac
#
