#!/bin/bash
#
# grep_error_patterns
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.2 2011-08-18
#

EXE="$0"

CFG="/etc/ClusterTools2/grep_error_patterns"
test -s $CFG && source $CFG

DMSG="/tmp/dmesg.$RANDOM"

test -z "${SYSTEM_LOG}" &&\
	 SYSTEM_LOG="/var/log/messages /var/log/boot.msg /var/log/boot.omsg /var/spool/mail/root /proc/mdstat /proc/net/bonding/bond0"
	 SYSTEM_LOG="${SYSTEM_LOG} ${DMSG}"

test -z "/etc/corosync/corosync.conf" &&\
test -z "${CLUSTER_LOG}" &&\
	 CLUSTER_LOG=$(grep "logfile:.*/" /etc/corosync/corosync.conf |\
		 tr -d "    " | cut -d":" -f2)

test -z "${ZIPPED_LOG}" &&\
	ZIPPED_LOG="/var/log/messages*bz2"
	ZIPPED_LOG="${ZIPPED_LOG} ${CLUSTER_LOG}*bz2"

test -z "${ERROR_PATTERN}" &&\
	 ERROR_PATTERN="
"taint.flag"
"no.device.*found"
"be2net.*Error"
"bfa.*err"
"lpfc.*err"
"qla.*err"
"qla.*failed"
"qlge.*error"
"NMI.received"
"NMI.*error"
"target.failure"
"reservation.conflict"
"SCSI.*reset"
"LUN.larger"
"I/O.error"
"disabling.*barrier"
"doesn.*support.*DPO.*FUA"
"Unable.*SMART.enabled"
"multipathd.*timed.out"
"multipathd:.mpath.*unable"
"multi.*path.*down"
"multipathd.*reinstated"
"[Ff]ail.*/dev/md"
"U_\|_U"
"found.0.matching.devices"
"/dev/md.*failed"
"duplicate.VG"
"duplicate.PV"
"not.found"
"dlm.*link.*down"
"ocfs2.*has.evicted"
"ocfs2.*ERR"
"ocfs2.*not.unmounted.cleanly"
"fsck.*recommended"
"EXT.-fs.error"
"iSCSI.connection.*error"
"bond.*link.*down"
"bond.*duplicate.address"
"bond.*not.detect.*failures"
"bond.*permanent.HWaddr.*in.use"
"Link.Failure.Count"
"link.*not.ready"
"link.failure"
"ntpd.*failed"
"ntpd.*time.reset"
"failed.to.bind.to.LDAP"
"refused.mount.request"
"logrotate.*error"
"Failed.to.read"
"exits.with.status.*[1-9]"
"Failed.services.*runlevel"
"shutdown.*shutting.down"
"syslog-ng.shutting.down"
"GAB.*failure"
"Symantec.Technical.Support"
"
# TODO: raid.set.*active.with.2.out.of.2.mirrors ?
# TODO: check for un-matched userfreindly names (mpath[a-z])
# TODO: pattern for failed module (could not load)
# TODO: async IO from grep kio /proc/slabinfo ?
# TODO: direct IO from grep ...,DIR, /proc/slabinfo ?
# TODO: verify cluster log msgs. maybe more generic possible ?

test -z "${CLUERR_PATTERN}" &&\
	 CLUERR_PATTERN="
"TOTEM.*FAILED.*RECEIVE"
"TOTEM.*processor.failed"
"TOTEM.*Incrementing.problem"
"quorum.lost"
"fenced.because.*.un-expectedly.down"
"stonith.*Device.*not.fond"
"Node.*unclean"
"pengine.*fenced.*resource.failure"
"pengine.*Forcing.*away.*failures"
"crm_resource.*Error"
"crmd.*ERROR:"
"crmd.*Updating.failcount.*stop"
"crmd.*Updating.failcount.*start"
"sbd.*mbox.read.failed"
"sbd.*Latency"
"SoftDog.*not"
"


function help() {
	echo "usage:	$(basename $0)"
	echo "	$(basename $0) [OPTION]"
	echo
	echo " --help		show help."
	echo " --version	show version."
	echo " --zip		search compressed logs, too."
}


function run_grep() {
	echo "logs: $LOG" >/dev/stderr

	dmesg >$DMSG

	# TODO: more efficient loop
	for e in ${ERROR_PATTERN} ${CLUERR_PATTERN}; do
        	echo -n "$e = "
		for f in ${LOG}; do
			test -r $f && cat $f
		done | zgrep -ic $e
	done

	rm $DMSG
}


# main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
        	head -11 $EXE | grep "^# Version: "
		exit
	;;
	-h|--help)
		help
		exit
	;;
	-z|--zip)
		LOG="${SYSTEM_LOG}"
		test -s ${CLUSTER_LOG} && LOG="${LOG} ${CLUSTER_LOG}"
		for z in ${ZIPPED_LOG}; do
			test -s $z && LOG="${LOG} ${z}"
		done
		run_grep
		exit
	;;
	*)
		LOG="${SYSTEM_LOG}"
		test -s ${CLUSTER_LOG} && LOG="${LOG} ${CLUSTER_LOG}"
		run_grep
		exit		
	;;
esac
#
