#!/bin/sh
#
# list_failcounts
#
# (c) 2009-2010 SUSE Linux GmbH, Germany. Author: F.Herschel.
# GNU Public License. No warranty.
#

#NODES=`cl_status listnodes -n`
CRM_RESOURCE=/usr/sbin/crm_resource
CRM_FAILCOUNT=/usr/sbin/crm_failcount
NODES=$(crm_node -A -l | awk '/member/ { print $2 }')
RESOURCES=$($CRM_RESOURCE -l )

echo DBG:
echo "$RESOURCES"


for node in $NODES
        do
        echo
        echo "Node: $node"
        echo
        for resource in $RESOURCES
                do
                echo -n "Resource $resource: "
 #               failcount=`$CRM_FAILCOUNT -G -U $node -r $resource | awk '{ print $2 }' | cut -d= -f2`
#		failcount=$($CRM_FAILCOUNT -G -U $node -r $resource | sed -e "s/^.*value=\(([0-9][0-9]*|INFINITY)\).*/\1/")
		failcount=$($CRM_FAILCOUNT -G -U $node -r $resource | awk -F= '{ for(i=1; i<NF; i++) { if ( $i ~ /value/ ) { i++; print $i; }}}')
                echo $failcount
        done
done
#
