#!/bin/bash
#
# make_sbd_devices
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: L.Pinne
#
# Version: 0.01 2011-07-16 14:20
#

EXE="$0"

CFG="/etc/ClusterTools2/make_sbd_devices"
test -s $CFG && source $CFG

SBD_OPTS=${2:-"-4 130 -1 30"}
SBD_CONF=${3:-"/etc/sysconfig/sbd"}

TMP="/tmp/cltl.$RANDOM"


function help(){
	echo "usage: $(basename $0) [OPTION]"
	echo "usage: $(basename $0) --init [SBD_OPTS [SBD_CONF]]"
	echo
	echo "OPTION:"
	echo " --dump		show content of SBD devices."
	echo " --help		show help."
	echo " --version	show version."
	echo " --init		initialise SBD devices."
	echo " --guess		guess SBD config file, write it."
	echo
}


function guess_sysconfig_sbd() {
	echo "INFO: start $EXE $FUNCNAME"
	
	grep "^SBD_DEVICE=/dev/.*;/dev/.*;/dev/" $SBD_CONF 2>/dev/null &&\
	echo "WARN: $SBD_CONF already exists" && return 2
	
	cp -a $SBD_CONF $SBD_CONF.bak 2>/dev/null

	echo "# $SBD_CONF" >$SBD_CONF
	echo -n "# check SBD_DEVICE for correct pathes and order" >>$SBD_CONF

	# TODO use devices from defaults
	#test -z "SBD_DEVS" 

	echo -n "SBD_DEVICE=\"" >>$SBD_CONF

	# TODO do this better 
	SBDEV=$(multipath -ll | grep -B1 "size=..M" |\
		awk '$2~/dm-/ {print "/dev/disk/by-id/scsi-"$1";"}' |\
		head -3 | tr -d "\n" | sed s/\;$// ) 

	echo -n $SBDEV >>$SBD_CONF
	echo "\"" >>$SBD_CONF

	echo "# watchdog support" >>$SBD_CONF
	# TODO use start opts from defaults	
	echo "SBD_OPTS=\"-W -1 30\"" >>$SBD_CONF
	echo "#" >>$SBD_CONF

	echo "INFO: end $EXE $FUNCNAME"
}


function make_sbd_devices() {
	echo "INFO: start $EXE $FUNCNAME"
	
	FIL=${SBD_CONF}
	test -s $FIL || exit 4
	grep "^SBD_DEVICE=" $FIL >/dev/null || exit 5

	awk -F"=" '$1=="SBD_DEVICE" {print $2}' $FIL |tr -d "\""|tr ";" "\n"|\
	while read; do
		sbd -d $REPLY ${SBD_OPTS} create
	done
	echo "INFO: end $EXE $FUNCNAME"
}

function dump_sbd_devices() {
	FIL=${SBD_CONF}

	awk -F"=" '$1=="SBD_DEVICE" {print $2}' $FIL |tr -d "\""|tr ";" "\n"|\
	while read; do
		sbd -d $REPLY dump
		sbd -d $REPLY list 
	done
}


# function main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-d|--dump)
		dump_sbd_devices
	;;
	-g|--guess)
		echo "INFO: start $EXE"

		guess_sysconfig_sbd

		echo "INFO: normal_end $EXE"
	;;
	-i|--init)
		echo "INFO: start $EXE"

		make_sbd_devices

		echo "INFO: normal_end $EXE"
	;;
	*)
		help
		exit
	;;
esac
#
