#!/bin/bash
#
# make_sbd_devices
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: L.Pinne
#
# Version: 0.02 2011-07-16 17:20
#

#set -x

EXE="$0"
TMP="/tmp/cltl.$RANDOM"
CFG="/etc/ClusterTools2/make_sbd_devices"
test -s $CFG && source $CFG


function help(){
	echo "usage: $(basename $0) [OPTION]"
	echo "usage: $(basename $0) --init [SBD_OPTS [SBD_CONF]]"
	echo
	echo "OPTION:"
	echo " --dump		show content of SBD devices."
	echo " --help		show help."
	echo " --version	show version."
	echo " --init		initialise SBD devices."
	echo " --guess	guess SBD config file."
	echo
}


function guess_sysconfig_sbd() {
	echo "INFO: start $EXE $FUNCNAME"
	
	CFI=${SBD_CONF}
	CFO=${SBD_CONF}
	#CFO="/dev/stdout"

	grep "^SBD_DEVICE=\"/dev/.*\"$" $CFI >/dev/null 2>&1 &&\
	# TODO use correct number of devives
	# grep "^SBD_DEVICE=\"/dev/.*;/dev/.*;/dev/.*\"$" $CFI >/dev/null 2>&1 &&\
	echo "WARN: $SBD_CONF already exists" && return 2

	cp -a $CFI $CFI.bak 2>/dev/null

	test -z "${SBD_DEVICE}" || SBDEV=${SBD_DEVICE}
	test -z "$SBDEV" || test -s $SBD_GUESS || exit 6
	SBDEV=$( exec $SBD_GUESS 2>/dev/null )
	test -z "$SBDEV" &&\
	{	# TODO do this better
		SBDEV=$( multipath -ll | grep -B1 "size=..M" |\
		awk '$2~/dm-/ {print "/dev/disk/by-id/scsi-"$1";"}' |\
		head -3 | tr -d "\n" | sed s/\;$// )
	}
	test -z "${SBD_OPTS}" || SBDOPT=${SBD_OPTS}
	test -z "${SBDOPT}" || SBDOPT="-W -1 30"
	{ 
	echo "# $CFI"
	echo "# check SBD_DEVICE for correct pathes and order"
	echo  "SBD_DEVICE=\"${SBDEV}\""
	echo "# watchdog support"
	# TODO use start opts from defaults
	echo "SBD_OPTS=\"${SBDOPT}\""
	echo "#"
	} >$CFO

	echo "INFO: end $EXE $FUNCNAME"
}


function make_sbd_devices() {
	echo "INFO: start $EXE $FUNCNAME"
	CFI=${SBD_CONF}
	test -s $CFI || exit 4
	grep "^SBD_DEVICE=" $CFI >/dev/null || exit 5
	awk -F"=" '$1=="SBD_DEVICE" {print $2}' $CFI |tr -d "\""|tr ";" "\n"|\
	while read; do
		sbd -d $REPLY ${SBD_INIT_OPTS} create
	done
	echo "INFO: end $EXE $FUNCNAME"
}


function dump_sbd_devices() {
	CFI=${SBD_CONF}

	awk -F"=" '$1=="SBD_DEVICE" {print $2}' $CFI |tr -d "\""|tr ";" "\n"|\
	while read; do
		sbd -d $REPLY dump
		sbd -d $REPLY list 
	done
}


# function main()

case $1 in
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	-d|--dump)
		dump_sbd_devices
	;;
	-g|--guess)
		echo "INFO: start $EXE"
		guess_sysconfig_sbd
		echo "INFO: normal_end $EXE"
	;;
	-i|--init)
		echo "INFO: start $EXE"
		test -z "${2}" && SBD_INIT_OPTS="${2}"
		test -z "${3}" && SBD_CONF="${3}"
		test -z "${SBD_INIT_OPTS}" &&\
			SBD_INIT_OPTS="-4 130 -1 30"
		test -z "${SBD_CONF}" &&\
			 SBD_CONF="/etc/sysconfig/sbd"
		make_sbd_devices
		echo "INFO: normal_end $EXE"
	;;
	*)
		help
		exit
	;;
esac
#
