#!/bin/bash
#
# make_iscsi_conf
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: A.Rehg, H.Bertram, L.Pinne.
#
# Version: 0.02 2011-06-25
#

EXE="$0"
CFG="/etc/ClusterTools2/make_iscsi_conf"
test -s $CFG && source $CFG

TMP="/tmp/cltl.$RANDOM"

ISCSI_CFG="/etc/iscsi/iscsid.conf"
test -z ${INITIATOR_CFG} && INITIATOR_CFG="/etc/iscsi/initiatorname.iscsi"
test -z ${INI_NETW} && INI_NETW=$(hostname -d | perl -e 'chomp($ar = <STDIN>); print join(".", reverse(split(/\./, $ar))), "\n";')
INITIATORNAME=iqn.$(date +%Y-%m).${INI_NETW}:$(hostname):0

# TODO: fill empty vars from config file


function fix_iscsid_conf() {
  echo "INFO: start $EXE $FUNCNAME"
 
  MOD="automatic"
  CFIL=$ISCSI_CFG
  OFIL=$CFIL
  BAK=${CFIL}.bak

  grep "^node.startup.*$MOD" $CFIL >/dev/null 
  RC=$?

  if [ $RC -gt 0 ]; then
  	cp $CFIL $BAK || exit $?
  	awk '	$1=="node.startup" {print $1,$2,"'"$MOD"'"}
		$1!="node.startup" {print}' $BAK >$OFIL
  else
	echo "WARN: found \"${MOD}\" already in ${CFIL}"
  fi 

  echo "INFO: end $EXE $FUNCNAME"
}


function fix_initiatorname() {
  echo "INFO: start $EXE $FUNCNAME"

  INI_UUID=$HOSTNAME
  #INI_UUID=$(uuidgen -r | awk -F"-" '{print $5}')
  INI_DATE=$(date +%Y-%m)

  CFIL=$INITIATOR_CFG
  OFIL=$CFIL
  BAK=${CFIL}.bak

  cp $CFIL $BAK
  awk -F"=" '	$1=="InitiatorName" {print $1"=""'"$INITIATORNAME"'"}
        	$1!="InitiatorName" {print}' $BAK >$OFIL

  echo "INFO: end $EXE $FUNCNAME"
}


# function main()

case $1 in
	-h|--help)
		echo "usage: $(basename $0) [OPTION]"
		echo
		echo "OPTION:"
		echo " --help		show help."
		echo " --version	show version."
		exit
	;;
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	*)
		echo "INFO: start $EXE"

		fix_iscsid_conf
		fix_initiatorname

		echo "INFO: normal_end $EXE"
	;;
esac
#
