#!/bin/bash
#
# make_iscsi_conf
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: A.Rehg, H.Bertram, L.Pinne.
#
# Version: 0.02 2011-06-25
#

EXE="$0"
CFG="/etc/ClusterTools2/make_iscsi_conf"
test -s $CFG && source $CFG

TMP="/tmp/cltl.$RANDOM"

ISCSI_CFG="/etc/iscsi/iscsid.conf"
test -z ${INITIATOR_CFG} && INITIATOR_CFG="/etc/iscsi/initiatorname.iscsi"
test -z ${INI_NETW} && INI_NETW=$(hostname -d | perl -e 'chomp($ar = <STDIN>); print join(".", reverse(split(/\./, $ar))), "\n";')
# f.e InitiatorName=iqn.1996-04.de.suse:01:1d635b8070c2	
INITIATORNAME=iqn.$(date +%Y-%m).${INI_NETW}:$(hostname):0

# TODO: fill empty vars from config file


function fix_iscsid_conf() {
  echo "INFO: start $EXE $FUNCNAME"
 
  MOD="automatic"
  CFIL=$ISCSI_CFG
  BAK=${CFIL}.bak

  grep "^node.startup.*$MOD" $CFIL >/dev/null 
  RC=$?

  if [ $RC -gt 0 ]; then
  	cp $CFIL $BAK || exit $?
  	awk '	$1=="node.startup" {print $1,$2,"'"$MOD"'"}
		$1!="node.startup" {print}' $BAK >$CFIL
  else
	echo "WARN: found \"${MOD}\" already in ${CFIL}"
  fi 

  echo "INFO: end $EXE $FUNCNAME"
}


function fix_initiatorname() {
  echo "INFO: start $EXE $FUNCNAME"

  CFIL=$INITIATOR_CFG
  BAK=${CFIL}.bak

  echo CFIL: $CFIL
  cp $CFIL $BAK >/dev/null
  grep "^InitiatorName=" $CFIL >/dev/null &&\
	echo "WARN: found InitiatorName already in ${CFIL}"

  awk -F"=" '	$1!="InitiatorName" {print "InitiatorName=""'"$INITIATORNAME"'"}
        	$1=="InitiatorName" {print}' $BAK >$CFIL

  echo "INFO: end $EXE $FUNCNAME"
}


function make_account(){
	echo "INFO: start $EXE $FUNCNAME"

	# TODO portal var
	ISCSI_PRT="10.4.17.2"
	ISCSI_CLSTR="hpsgeval1-hpsgeval2"
	ISCSI_TGT=$(iscsiadm --mode discovery --type sendtargets --portal ${ISCSI_PRT} |\
		grep ".$ISCSI_CLSTR:" | awk -F" " '{print $2}' )
	ISCSI_USR="$ISCSI_CLSTR"
	ISCSI_PWD="$ISCSI_CLSTR"
	# iscsiadm --mode discovery --type sendtargets --portal ${ISCSI_PRT} 
	echo "iscsiadm -m node -T ${ISCSI_TGT} --op update -n node.conn[0].startup -v automatic"
	echo "iscsiadm -m node -T ${ISCSI_TGT} --op update \
		-n node.session.auth.username -v ${ISCSI_USR}"
	echo "iscsiadm -m node -T ${ISCSI_TGT} --op update \
		-n node.session.auth.password -v ${ISCSI_PWD}"
	
	echo "INFO: end $EXE $FUNCNAME"
}


# function main()

case $1 in
	-h|--help)
		echo "usage: $(basename $0) [OPTION]"
		echo
		echo "OPTION:"
		echo " --help		show help."
		echo " --version	show version."
		exit
	;;
	-v|--version)
		echo -n "$(basename $EXE) "
		head -11 $EXE | grep "^# Version: "
		exit
	;;
	*)
		echo "INFO: start $EXE"

		fix_iscsid_conf
		fix_initiatorname
		make_account

		echo "INFO: normal_end $EXE"
	;;
esac
#
