#!/bin/bash
#
# prepare_wowfile
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.01 2011-07-21
#

EXE=$(basename $0)
DAT=$(date +"%F %T")

function help() {
	echo "usage:	$EXE --sap <SID> [<SVC_LABEL>]"
	echo "	$EXE --ora <SID> <SVC_LABEL> [<VG>]"
	echo "	$EXE --help|--version"
	exit
}


function version() {
	echo -n "$EXE "
	head -11 $EXE | grep "^# Version: "
}


function get_header() {
	echo "# $DAT - $EXE $*"
}


function get_storage_sap() {
	# TODO better string manipulation
	echo -n "RAID1_DEVICES=\""
	pvs | awk '$2~/'"$SID"'/ {print $1" "}' | tr -d "\n" | sed s/" "$//
	echo "\""
	echo
	#
	echo -n "LVM_VOLUMEGROUPS=\""
	pvs | awk '$2~/'"$SID"'/ {print $2" "}' | sort -du | tr -d "\n" | sed s/" "$//
	echo "\""
	echo
	#
	echo 'FS_FILESYSTEMS=$(cat <<HERE-FS'
	mount | awk '$1~/\/'"$SID"'/ {	n=split($3,label,"/")
		print $1,$3,label[n-2]"-"label[n-1]"-"label[n],$5,"noatime,defaults"}'
	echo 'HERE-FS'
	echo ')'
}


function get_storage_ora() {
	# TODO better string manipulation
	echo -n "RAID1_DEVICES=\""
	pvs | awk '$1~/^\/dev\/md.$/ && $2~/^'"$VG"'/ {print $1" "}' | tr -d "\n" | sed s/" "$//
	echo "\""
	echo
	#
	echo -n "LVM_VOLUMEGROUPS=\""
	pvs | awk '$1~/^\/dev\/md.$/ && $2~/^'"$VG"'/ {print $2" "}' | sort -du | tr -d "\n" | sed s/" "$//
	echo "\""
	echo
	#
	echo 'FS_FILESYSTEMS=$(cat <<HERE-FS'
	mount | awk '$1~/\/dev\/.*\/'"$VG"'-lv/ && $3~/^\/'"$VG"'lv/ { print $1,$3,"noatime,defaults"}'
	echo 'HERE-FS'
	echo ')'
}


function get_network() {
	echo
	echo "ALLNODES=\"$HOSTNAME\""
	echo
	echo -n "IP_LABELS=\""
	host $SVCNAM | awk '$1~/'"$SVCNAM"'/ {print "'"$SVCNAM"',"$4"\""}'
}


function get_sys_sap() {
	echo
	echo "SAPSID=\"$SID\""
	echo "DBTYPE=ORA"
	echo "GRPID=grp_sap_$SID"
	echo "SAP_SCORES=\"1000 0\""
	echo
}


function get_sys_ora() {
	echo
	echo "ORASID=\"$SID\""
	echo "DBTYPE=ORA"
	echo "GRPID=grp_ora_$SID"
	echo "SAP_SCORES=\"1000 0\""
	echo
}


# main()

case $1 in
	-v|--version)
		version
	;;
	-o|ora|oracle)
		shift
		SID=${1:-"ora01"}	
		SVCNAM=${2:-"ora01"}
		VG=${3:-"vg01"}
		
		get_header "${*}"
		get_network
		get_sys_ora
		get_storage_ora
		echo "#"
	;;
	-s|sap)
		shift
		SID=${1:-"ZSAdb"}
		SVCNAM=${2}
		test -z "$SVCNAM" && SVCNAM=$(echo $SID|tr [:upper:] [:lower:])

		get_header "${*}"
		get_network
		get_sys_sap
		get_storage_sap
		echo "#"
	;;
	-h|--help|*)
		help
	;;
esac
#
