#!/bin/bash
#
# prepare_wowfile
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.01 2011-03-04
#

SID=${1:-"ZSAdb"}
SVCNAM=${2}
test -z "$SVCNAM" && SVCNAM=$(echo $SID|tr [:upper:] [:lower:])

EXE=$(basename $0)

function help() {
	echo "usage:	$EXE <SID>"
	echo "	$EXE <SID> <SVC_LABEL>"
	echo "	$EXE -h|-v"
	exit
}


function version() {
	head -11 $EXE | grep "^# Version: "
}


function storage() {
	echo -n "RAID1_DEVICES=\""
	pvs | awk '$2~/'"$SID"'/ {print $1" "}' | tr -d "\n"
	echo "\""
	echo
	#
	echo -n "LVM_VOLUMEGROUPS=\""
	pvs | awk '$2~/'"$SID"'/ {print $2" "}' | sort -du | tr -d "\n"
	echo "\""
	echo
	#
	echo 'FS_FILESYSTEMS=$(cat <<HERE-FS'
	mount | awk '$1~/\/'"$SID"'/ {	n=split($3,label,"/")
		print $1,$3,label[n-2]"-"label[n-1]"-"label[n],$5,"noatime,defaults"}'
	echo 'HERE-FS'
	echo ')'
}


function network() {
	echo
	echo "ALLNODES=\"$HOSTNAME\""
	echo
	echo -n "IP_LABELS=\""
	host $SVCNAM | awk '$1~/'"$SVCNAM"'/ {print "'"$SVCNAM"',"$4"\""}'
}


function sapsys() {
	echo
	echo "SAPSID=\"$SID\""
	echo "DBTYPE=ORA"
	echo "GRPID=grp_sap_$SID"
	echo "SAP_SCORES=\"1000 0\""
	echo
}


# main()

case $1 in
	-h|--help)
		help
	;;
	-v|--version)
		version
	;;
	*)
		network
		sapsys
		storage
	;;
esac
#
