#!/bin/sh
#
# reset_failcounts
#
# (c) 2009-2010 SUSE Linux GmbH, Germany. Author: F.Herschel.
# GNU Public License. No warranty.
#

#NODES=`cl_status listnodes -n`
NODES=$(crm_node -A -l | awk '/member/ { print $2 }')

CRM_RESOURCE=/usr/sbin/crm_resource
CRM_FAILCOUNT=/usr/sbin/crm_failcount
RESOURCE=$($CRM_RESOURCE -l )

for node in $NODES
        do
        echo
        echo "Node: $node"
        echo
        for resource in $RESOURCE
                do
                echo -n "Resource $resource: "
		failcount=$($CRM_FAILCOUNT -G -U $node -r $resource | awk -F= '{ for(i=1; i<NF; i++) { if ( $i ~ /value/ ) { i++; print $i; }}}')
                echo "==" $failcount

		case "$failcount" in
			INFINITY | [1-9]* )
			echo -n " -> Failcount greater 0, resetting failcount: "
			$CRM_FAILCOUNT -D -U $node -r $resource
			echo "done"
			;;
		esac
	done
done
#
