#!/bin/bash
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.1 2011-02-15
#
# For SLES11.

FIL="
/var/lib/corosync/*
/var/lib/heartbeat/cores/*/*
/var/lib/heartbeat/crm/*
/var/lib/pengine/*
"
BAK="/var/adm/backup/cib.xml-$(date +%Y%m%d-%H%M%S)"
EXE=$0

function version() {
        head -11 $EXE | grep "^# Version: "
}

case $1 in
	-v|--version)
		version
		exit
	;;
	--force)
		rcopenais stop || exit

		mv /var/lib/heartbeat/crm/cib.xml $BAK 
		for f in $FIL; do
			rm -f $f
		done
	;;
	*)
		echo "usage: $(basename $0) [OPTION]"
		echo
		echo " --force	stop cluster servcie and resources, remove CIB and PE logs."
		echo " --help		show help."
		exit
	;;
esac
#
