#!/bin/bash
#
# (c) 2011 SUSE Linux GmbH, Germany. Author: L.Pinne.
# GNU Public License. No warranty.
#
# Version: 0.1 2011-03-07
#
# For SLES11.

FIL="
/var/lib/corosync/*
/var/lib/heartbeat/cores/*/*
/var/lib/heartbeat/crm/*
/var/lib/pengine/*
"
BAK="/var/adm/backup/cib.xml-$(date +%Y%m%d-%H%M%S)"
EXE=$0


case $1 in
	-v|--version)
        	head -11 $EXE | grep "^# Version: "
		exit
	;;
	--force)
		rcopenais stop || exit

		mv /var/lib/heartbeat/crm/cib.xml $BAK 
		for f in $FIL; do
			rm -f $f
		done
		exit
	;;
	*)
		echo "usage: $(basename $0) [OPTION]"
		echo
		echo " --force	stop cluster service and resources, remove CIB and PE logs."
		echo " --help		show help."
		echo " --version	show version."
		exit
	;;
esac
#
