#!/bin/bash
#
# guess_sbd_devices
#
# (c) 2011 SUSE Linux GmbH, Germany.
# GNU Public License. No warranty.
# Author: L.Pinne
#
# Version: 0.01 2011-07-20 17:00
#
# TODO do this better
multipath -ll | grep -B1 -P "^size=\d(\d|\.\d)M" |\
awk '$2~/dm-/ {print "/dev/disk/by-id/scsi-"$1";"}' |\
head -3 | sort | tr -d "\n" | sed s/\;$//
#
