#!/bin/bash
#
# wowlib2
#
# (c) 2009-2012 SUSE Linux GmbH, Germany. Author: F.Herschel.
# GNU Public License. No warranty.
#
# Version: 0.2 2012-02-10
#
set +u
only_members=0
#
# call specific setup
#
if [ -z "$WOW_SIMULATE" ]; then 
	WOW_SIMULATE=yes
fi

#
# scan command line
#
while [ $# -gt 0 ]; do
	case "$1" in
		--config )
			config="$2"
			shift
			;;
	        --members ) only_members=1;
			;;
	esac
	shift
done
#
##############################
#
# some defaults
#
export SFEXID=1
export SFEX_INDEX=1
export SFEX_DEVICE=""
export DEFAULT_RESOURCE_STICKINESS=1000
export DEFAULT_MIGRATION_THRESHOLD=5
export DEFAULT_ACTION_TIMEOUT=120s
export DEFAULT_IPagent=IPaddr2
export STONITH_ENABLED=true
#

if [ -n "$config" ]; then
	source $config
else
	echo "FATAL ERROR: No config file specified"
	echo "Please use option '--config configfile'"
        exit 2
fi

set -u
##############################
#
# wow generic setup
#
 #WOWRSRCECREATE="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=resources CIBACTION=-C"
 #WOWRSRCEMODIFY="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=resources CIBACTION=-M"

 #WOWCONFGCREATE="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=crm_config CIBACTION=-C"
 #WOWCONFGMODIFY="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=crm_config CIBACTION=-M"
 #WOWCONFGUPDATE="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=crm_config CIBACTION=-U"

 #WOWCONSTCREATE="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=constraints CIBACTION=-C"
 #WOWCONSTMODIFY="WOW_SIMULATE=$WOW_SIMULATE CIBREMOTE=$CIBREMOTE CIBOBJTYPE=constraints CIBACTION=-M"

wowcli=${wowcli:-/usr/share/ClusterTools2/cli}

function set_var()
{
        local var value
        var=$1
        value="$2"
        var=$(echo ${var} | tr '-' '_')
        eval export $var=\"\$value\"
}

function get_var()
{
        local var
        var=$1
        var=$(echo ${var} | tr '-' '_')
        echo $var
}

function firstof_var()
{
        local var value help
        var=$1
        eval value=\${$var%% *}
        echo "$value"
}

function shift_var()
{
        local var value help help2
        var=$1
        eval value=\${$var%% *}
        eval help=\${$var#* }
        help2=0
        eval test \"\$help\" == \"\$${var}\" && help2=1
        if [ $help2 -eq 0 ]
        then
           eval export $var=\"\$help\"
        else
           eval export $var=\"\"
        fi
        return $help2
}

