#!/bin/bash
#
# check4config_files
# (c) 2012 SUSE Linux Products GmbH, Nuremberg, Germany
# Author: Fabian Herschel
# License: GPL

CFG_FILES=$(awk -F'["=]' '/CFG=.*etc\/ClusterTools2/ {print $3}' sbin/*)

for cfg in ${CFG_FILES}; do
	if [ ! -f "${cfg#/}" ]; then
		echo "${cfg#/} MISSING"
	fi
done
