#!/bin/bash
# /usr/lib/supportconfig/plugins/cat_sapstacklog
# Version: 2026-10-01

PLUG="cat_sapstacklog"
CONF="/etc/ClusterTools2/supportconfig_plugins"
LOGF="/var/log/sapstack.log"
ZLOG="/var/log/sapstack.log*bz2"

grep "^${PLUG}$" $CONF >/dev/null || exit 0 

echo "### $LOGF ###"
test -r $LOGF && cat $LOGF
for f in $ZLOG; do
	echo "### $f ###"
	test -r "$f" && bzcat "$f"
done
echo "Completed"
#
