#!/bin/bash
# /usr/lib/supportconfig/plugins/cat_dstatelog
# Version: 2026-09-26

PLUG="cat_dstatelog"
CONF="/etc/ClusterTools2/supportconfig_plugins"
LOGF="/var/log/dstate.log"
ZLOG="/var/log/dstate.log*bz2"

grep "^${PLUG}$" $CONF >/dev/null || exit 0 

echo "### $LOGF ###"
test -r $LOGF && cat $LOGF
for f in $ZLOG; do
	echo "### $f ###"
	test -r "$f" && bzcat "$f"
done
echo "Completed"
#
