#!/bin/bash
#
# ClusterTools2-timer
#
# Version: 2026-08-15
#
/usr/sbin/meminfolog /var/log/meminfo.log
/usr/sbin/vmstatlog /var/log/vmstat.log
/usr/sbin/lsoflog /var/log/lsof.log "+D/opt +D/srv +D/home"
/usr/sbin/psauxlog /var/log/psaux.log
#
