#!/bin/bash
#
# cs_dmesg
#
# (c) 2011-2017 SUSE Linux GmbH, Germany.
# (c) 2018-2019 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2019-12-05 SLES12
#

EXE="$0"

# main()
case $1 in
	-h|--help)	
		echo "usage:	$(basename "$EXE") [OPTION]"
		echo "usage:	$(basename "$EXE")"
		echo " --help		show help"	
		echo " --version	show version"
		exit
	;;
	-v|--version)
		echo -n "$(basename "$EXE") "
		head -11 "$EXE" | grep "^# Version: "
		exit
	;;
	*)
		D=$(date +%s)
		U=$(uptime | tr -d "," |\
		awk 'NF==10{f=split($3,a,":"); print 60*60*a[1]+60*a[2]} 			NF==12{f=split($5,a,":"); print 24*60*60*$3+60*60*a[1]+60*a[2]}')
		B=$((D - U))
		dmesg | awk '{E=int($2+'"$B"'); system("T=$(/bin/date -d @"E"); echo -n $T"); print "  "$0}'
	;;
esac
#
