#!/bin/bash
#
# cs_stop_all_sap
#
# (c) 2026 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2026-06-19
#
# not for HANA scale-out
#
# sapcontrol return codes
# 0 Last webmethod call successful
# 1 Last webmethod call failed, invalid parameter
# 2 StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait timed out
# 3 GetProcessList succeeded, all processes running correctly
# 4 GetProcessList succeeded, all processes stopped
# set -x

EXE="$0"
TIMEOUT=${2:-600}
RETCODE=0


function help() {
    echo "usage:    $(basename "$EXE") --stop [ <seconds> ]
    echo "usage:    $(basename "$EXE") [ --help | --version ]"
    echo "OPTION:"
    echo " --help               show help"
    echo " --version            show version info"
    echo " --stop [<seconds>]   stop all SAP instances [ WaitforStopped <seconds> ]"    
}


function get_sap_sid_ino() {
    test -x /usr/sap/hostctrl/exe/saphostctrl || exit 9
	/usr/sap/hostctrl/exe/saphostctrl -function ListInstances |\
	awk '{print $4,$6}'
}


function stop_all() {
    SAP=$(get_sap_sid_ino)
    while read; do
	    rc=1
	    SID=$(echo $REPLY | awk '{print $1}')
	    sid=${SID,,}
	    INO=$(echo $REPLY | awk '{print $2}')

	    echo "### $SID - $INO ###"	
	    su - ${sid}adm -c "sapcontrol -nr $INO -function GetProcessList" 
	    su - ${sid}adm -c "sapcontrol -nr $INO -function Stop"
        # TODO correct rc
	    su - ${sid}adm -c "sapcontrol -nr $INO -function WaitforStopped $TIMEOUT 10"; rc=$?
	    su - ${sid}adm -c "sapcontrol -nr $INO -function GetProcessList"
	    if [[ $rc -eq 4 ]] || [[ $rc -eq 0 ]]; then
           rc=0
	    fi
	    (( RETCODE = RETCODE + rc ))
	    echo
	    echo "### $SID - $INO rc: $rc ###"
    done <<< "$SAP"

    (( RETCODE = RETCODE * 10 ))
    echo RC: $RETCODE
    exit $RETCODE
}


# main()

case $1 in
    -v | --version)
        echo -n "$(basename "$EXE") "
        head -11 "$EXE" | grep "^# Version: "
    ;;
    -s | --stop)
        stop_all
    ;;
    *)
        help
    ;;
esac
#
