#!/bin/bash
#
# dstatelog
#
# (c) 2026 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 0.1 2026-09-25
#

D=$(date +"%F %T")
L=${1:-"/var/log/vmstat.log"}

echo w > /proc/sysrq-trigger
# dmesg -T | sed TODO | grep $D >>"$L"
#
