#!/bin/bash
#
# vmstatlog
#
# (c) 2026 SUSE LLC
# Author: L.Pinne.
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 0.1 2026-08-15
#

D=$(date +"%F %T")
L=${1:-"/var/log/vmstat.log"}

while read -r ; do
	echo "$D": "$REPLY"
done < /proc/vmstat >>"$L"
