#!/bin/bash
source wowlib2
 #
 # at this moment we only support ONE or ZERO SFEX device(s)
 #    will be enhanced in future? You can add multiple devices
 #    but all need to have the same index
 #
 for sfexdevicex in $SFEX_DEVICE
 do
	 woweng2 UUID=rsc_sfex_${SFEXID}_${SFEX_INDEX}_${SAPSID} \
		SFEX_INDEX=${SFEX_INDEX} SFEX_DEVICE=${SFEX_DEVICE} \
		$wowcli/01-sfex.cli
 done
