#!/bin/bash
DBTYPE=ORA
source wowlib2
 case "$DBTYPE" in
	ORA ) cli=01-sapdb_ora.cli
		;;
	* )   cli=01-sapdb.cli
		;;
 esac
 woweng2 UUID=rsc_sapdb_$SAPSID \
		SAPSID=$SAPSID  \
		DBTYPE=$DBTYPE \
		$wowcli/$cli
