.TH cs_show_saphanasr_status 8 "27 Jul 2020" "" "ClusterTools2"
.\"
.SH NAME
.\"
cs_show_saphanasr_status \- show status for SAPHanaSR cluster
.\"
.SH SYNOPSIS
.\"
\fBcs_show_saphanasr_status\fR
.P
\fBcs_show_saphanasr_status\fR [\fIOPTION\fR]
.\"
.SH DESCRIPTION
.\"
\fBcs_show_saphanasr_status\fP shows status overview for an SAPHanaSR cluster.
.\"
.SH OPTIONS
.\"
.TP
\fB--help\fR
show help
.TP
\fB--version\fR
show version
.\"
.SH EXAMPLES
.\"
.TP
* Show status overview for SAPHanaSR cluster:
.br
# cs_show_saphanasr_status | grep -v ^#
.br
.\"
.SH EXIT STATUS
.\"
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.\"
.TP
/usr/sbin/cs_show_saphanasr_status
the program itself
.\".TP
.\"/etc/ClusterTools2/cs_show_saphanasr_status
.\"the program's main configuration
.\"
.SH BUGS
.\"
No useful return codes implemented.
.br
Feedback is welcome, please mail to feedback@suse.com
.\"
.SH SEE ALSO
.\"
\fBcs_clusterstate\fP(8), \fBcs_show_hana_info\fP(8) ,
\fBSAPHanaSR-showAttr\fP(8), \fBcrm_mon\fP(8),
\fBClusterTools2\fP(7)
.\"
.SH COPYRIGHT
.\"
(c) 2020 L.Pinne, Germany.
.br
cs_show_saphanasr_status comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
