#!/bin/bash
# /usr/lib/supportconfig/plugins/cat_xmstat
# Version: 2013-05-08

PLUG="cat_xmstat"
CONF="/etc/ClusterTools2/supportconfig_plugins"
LOGF="/var/log/xmstat.log"
ZLOG="/var/log/xmstat.log*bz2"

grep "^${PLUG}$" $CONF >/dev/null || exit 0 

echo "### $LOGF ###"
test -r $LOGF && cat $LOGF
for f in $ZLOG; do
	echo "### $f ###"
	test -r $f && bzcat $f
done
echo "Completed"
#
