#!/bin/bash
# /usr/lib/supportconfig/plugins/precheck_for_hana

PLUG="precheck_for_hana"
CONF="/etc/ClusterTools2/supportconfig_plugins"

grep "^${PLUG}$" $CONF >/dev/null || exit 0

/usr/sbin/cs_precheck_for_hana -b 2>&1
#
