#!/bin/bash
# /usr/lib/supportconfig/plugins/precheck_for_sap

PLUG="precheck_for_sap"
CONF="/etc/ClusterTools2/supportconfig_plugins"

grep "^${PLUG}$" $CONF >/dev/null || exit 0

/usr/sbin/cs_precheck_for_sap -g 2>&1
#
