#!/usr/bin/perl -w
#
# http://stackoverflow.com/questions/95492/how-do-i-convert-a-date-time-to-epoch-time-aka-unix-time-seconds-since-1970
#

use strict;

$_ = (join ' ', @ARGV);
$_ ||= <STDIN>;

chomp;

if (/^[\d.]+$/) {
	print scalar localtime $_;
	print "\n";
}
else {
	exec "date -d '$_' +%s";
}
#
