#!/bin/bash
source wowlib2
for clx_application in $CLX_APPLICATION; do
	woweng2 UUID=rsc_clx_${SAPSID}_${clx_application} \
		APPLICATION=$clx_application \
		DEVICES=$CLX_DEVICE \
		$wowcli/01-clx.cli
done
