#!/bin/bash
IPagent=""
source wowlib2
if [ -z "$IPagent" ]; then
	IPagent=$DEFAULT_IPagent
fi
for ip_label in $IP_LABELS; do
	ipaddr=${ip_label#*,}
	ipname=${ip_label%,*}
	woweng2 GROUPID=${GRPID} \
		UUID=rsc_ip_${SAPSID}_${ipname} \
		IP=$ipaddr \
		IPagent="$IPagent" \
		$wowcli/01-ip.cli
done
