#!/bin/bash
IPagent=""
GROUP_MEMBERS=""
DBTYPE=""

source wowlib2
WOW_AGENTS_DIR=/usr/lib/ClusterTools2/agents
NGM=""
#
# sfex
#
for sfexdevicex in $SFEX_DEVICE;
do
  NGM="${NGM} rsc_sfex_${SFEXID}_${SFEX_INDEX}_$SAPSID"
done
GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
#
# ip
#
if [ -z "$IPagent" ]; then
	IPagent=$DEFAULT_IPagent
fi
for ip_label in $IP_LABELS; do
	ipaddr=${ip_label#*,}
	ipname=${ip_label%,*}
	NGM=rsc_ip_${SAPSID}_${ipname} 
	GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
done
#
# RAID1 / MD
#
GROUP_MEMBERS="$GROUP_MEMBERS $($WOW_AGENTS_DIR/01-04-add_md --config $config --members)"
#for raiddev in $RAID1_DEVICES; do
#	raidname=${raiddev#/dev/}
#	NGM=rsc_md_${SAPSID}_${raidname} 
#	GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
#done
#
# LVM
#
for volumegroup in $LVM_VOLUMEGROUPS; do
	NGM=rsc_lvm_${SAPSID}_${volumegroup} 
	GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
done
#
# FS
# 
while read dev dir fsid fstype moptions
do 
	if [ -n "${dev%%\#*}" ]; then # neither an empty line nor a comemnt line (# is first char)
		NGM=rsc_fs_${SAPSID}_${fsid} 
		GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
	fi
done <<< "$FS_FILESYSTEMS"
#
# DB
#
 case "$DBTYPE" in
	ORA ) cli=01-sapdb.ora.cli
		 NGM=rsc_sapdb_$SAPSID 
		;;
	ADA | DB2 | SYB )   cli=01-sapdb.cli
		 NGM=rsc_sapdb_$SAPSID 
		;;
	* ) # If unknown or empty we skip the DB resource
                NGM=""
		;;
 esac
GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
#
# SAPINST
#
if [ -n "$SAP_INSTANCE_DEF" ]; then
while read sap_type sap_inst sap_prof sap_parm; do
	if [ "$sap_type" == "${sap_type#\#}" ]; then
		NGM=rsc_sapinst_${sap_inst}  
		GROUP_MEMBERS="$GROUP_MEMBERS $NGM"
	fi
	done <<< "$SAP_INSTANCE_DEF"
fi

woweng2 UUID=${GRPID} \
    GROUP_MEMBERS="$GROUP_MEMBERS" \
    $wowcli/01-grp-sap.cli
#
# LOC
#

#
# sap scores per node
#
mySCORE=$SAP_SCORES
for node in $ALLNODES
do
        nSCORE=$(firstof_var mySCORE); shift_var mySCORE
        woweng2 UUID=loc_${GRPID}_on_${node} RESOURCE=$GRPID SCORE=$nSCORE  NODE=${node} $wowcli/03-loc.cli
#        woweng $WOWCONSTMODIFY CONSTID=loc_${GRPID}_on_${node} UUID=prefered_loc_${GRPID}_on_${node} SCORE=$nSCORE $wowxml/03-constraint_rule.xml
#        woweng $WOWCONSTMODIFY RULEID=prefered_loc_${GRPID}_on_${node} UUID=prefered_loc_${GRPID}_on_${node}_name ATTRIBUTE="#uname" OPERATOR="eq" VALUE="${node}" $wowxml/03-constraint_rule_expression.xml
done

