#!/bin/bash
# /usr/lib/supportconfig/plugins/messages

PLUG="cat_mesasges"
CONF="/etc/ClusterTools2/supportconfig_plugins"
LOGF="/var/log/messages"
ZLOG="/var/log/messages*bz2"

grep "^${PLUG}$" $CONF >/dev/null || exit 0 

echo "### $LOGF ###"
test -r $LOGF && cat $LOGF
for f in $ZLOG; do
	echo "### $f ###"
	test -r $f && bzcat $f
done
#
