#!/bin/bash
# /usr/lib/supportconfig/plugins/cat_messages
# Version: 2013-04-23

PLUG="cat_messages"
CONF="/etc/ClusterTools2/supportconfig_plugins"
LOGF="/var/log/messages /var/log/ntp"
ZLOG="/var/log/messages*bz2 /var/log/ntp*bz2"

grep "^${PLUG}$" $CONF >/dev/null || exit 0 

for f in $LOGF; do
	echo "### $f ###"
	test -r $f && cat $f
done
for f in $ZLOG; do
	echo "### $f ###"
	test -r $f && bzcat $f
done
echo "Completed"
#
