#!/bin/bash
# /usr/lib/supportconfig/plugins/cat_psauxlog

CONF="/etc/ClusterTools2/supportconfig_plugins"
PLUG="cat_psauxlog"
LOGF="/var/log/psaux.log"
ZLOG="/var/log/psaux.log*bz2"

grep "^${PLUG}$" $CONF >/dev/null || (echo "Skipping..."; exit) 

echo "### $LOGF ###"
test -r $LOGF && cat $LOGF
for f in $ZLOG; do
	echo "### $f ###"
	test -r $f && bzcat $f
done
#
