#!/bin/bash
# /usr/lib/supportconfig/plugins/hb_report

PLUG="hb_report"
CONF="/etc/ClusterTools2/supportconfig_plugins"

grep "^${PLUG}$" $CONF >/dev/null || exit 0

/usr/sbin/hb_report -S -f 00:00 2>&1
#
