#!/bin/bash
# /usr/lib/supportconfig/plugins/show_error_patterns

PLUG="show_error_patterns"
CONF="/etc/ClusterTools2/supportconfig_plugins"

grep "^${PLUG}$" $CONF >/dev/null || exit 0 

# TODO make -z an option in $CONF
/usr/sbin/cs_show_error_patterns -z 2>&1
#
