#!/bin/bash
# /usr/lib/supportconfig/plugins/sum_base_config

PLUG="sum_base_config"
CONF="/etc/ClusterTools2/supportconfig_plugins"

grep "^${PLUG}$" $CONF >/dev/null || exit 0

/usr/sbin/cs_sum_base_config 2>&1
#
