#!/bin/bash
#
# check4config_files
# (c) 2012 SUSE Linux Products GmbH, Nuremberg, Germany
# Author: Fabian Herschel
# License: GPL

BIN_FILES="sbin/*"

for bin in ${BIN_FILES}; do
	bin="${bin#sbin/}"
	mp="man8/${bin}.8"
	
	if [ ! -f "$mp" ]; then
		echo "MAN PAGE ${mp} MISSING"
	else
		#
		# checking, if title (.TH) and synopsis matches the binary name :)
		#
		awk 'BEGIN { rc=9; THfound=0; SYNfound=0 }
		      ( $0 ~ ".TH.*" bin ) { THfound=1; Synopsis=0 }
		      ( $0 ~ ".SH SYNOPSIS" ) { Synopsis=1; } 
		      ( $0 ~ ".B.*" bin ) && ( Synopsis==1 ) { Synopsis=0; SYNfound=1 } 
		     END { 
		          if ((SYNfound==1) && (THfound==1) ) {
			     rc=0
			  } else {
			          rc1=0; rc2=0;
				  if (!(THfound==1)) {
					  rc1=1;
			          }
				  if (!(SYNfound==1)) {
				    rc2=1;
			          }
				  rc=rc1*2+rc2;
			  }
		           exit rc 
		         } 
			 ' bin=$bin < $mp ; echo "MAN PAGE ${mp} ($bin) rc=$?"
	fi
done
