.TH cs_clusterstate 8 "27 Jul 2020" "" "ClusterTools2"
.\"
.SH NAME
cs_clusterstate \- show status of pacemaker HA cluster 
.\"
.SH SYNOPSIS
.B cs_clusterstate \fI[OPTION]\fR
.\"
.SH DESCRIPTION
\fBcs_clusterstate\fP TODO
.br
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help
.HP
\fB --version\fR
	show version
.HP
\fB --all\fR
	show all info
.HP
\fB --basics\fR
	show basics info
.HP
\fB --network\fR
	show network info
.HP
\fB --storage\fR
	show storage info
.HP
\fB --replication\fR
	show SAPHanaSR info
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/cs_clusterstate
	the program itself
.TP
/etc/ClusterTools2/cs_clusterstate
	the configuration
.\"
.SH BUGS
Currently very limited functionality.
No other STONITH than SBD is known.
No other data mirroring than MD RAID is known.
No other data replication than SAP HANA SR is known.
Feedback is welcome, please use the project page at
.br
Feedback is welcome, please mail to feedback@suse.com
.\"
.SH SEE ALSO
\fBClusterTools2\fP(7), \fBcs_show_saphanasr_status\fP(8),
\fBcrm_mon\fP(8),  \fBcorosync-cfgtool\fP(8), \fBethtool\fP(8),
\fBsbd\fP(8), \fBmdadm\fP(8), \fBSAPHanaSR-showAttr\fP(8)
.\"
.SH COPYRIGHT
(c) 2011-2020 L.Pinne, Germany.
.br
cs_clusterstate comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
