.TH cs_show_hana_info 8 "15 Apr 2021" "" "ClusterTools2"
.\"
.SH NAME
cs_show_hana_info \- show info about HANA instance
.\"
.SH SYNOPSIS
.P
.B cs_show_hana_info \fI[OPTION]\fR
.P
.B cs_show_hana_info \fI[OPTION]\fR \fI<SID>\fR \fI<inst_nr>\fR
.\"
.SH DESCRIPTION
\fBcs_show_hana_info\fP shows info about HANA instance.
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help
.HP
\fB --version\fR
	show version
.HP
\fB --info\fR
	show info for given instance
.HP
\fB --logs\fR
	show summary on errors in logs for given instance

.\"
.SH EXAMPLES
.br
.TP
* Show info about HANA instance with SID HDB and instance number 11 :
.br
# cs_show_hana_info --info HDB 11
.br
.TP
* Show summary on errors in logs from HANA instance with SID HDB and instance number 11 :
.br
# cs_show_hana_info -l HDB 11
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.SH FILES
.TP
/usr/sbin/cs_show_hana_info
	the program itself
.TP
/etc/ClusterTools2/cs_show_hana_info
        the program's main configuration
.TP
/usr/sap/<SID>/SYS/global/hdb/custom/config/global.ini
	HANA's global configuration file
.TP
/usr/sap/sapservices
	...
.TP
/hana/shared/<SID>/HDB<inst_nr>/<host>/trace/*.trc
	HANA services' trace files
.\"
.SH BUGS
Feedback is welcome, please mail to feedback@suse.com
.\"
.SH SEE ALSO
\fBsu\fP(1),
https://www.suse.com/support/kb/doc.php?id=7010056 ,
https://www.suse.com/support/kb/doc.php?id=7010249 ,
https://www.suse.com/support/kb/doc.php?id=7022702 ,
https://www.suse.com/support/kb/doc.php?id=7023007 ,
https://blogs.sap.com/2012/06/20/collecting-hana-support-information-easily/ ,
SAP notes 1732157, 2036111 , 2446324, 3007062 
.\"
.SH COPYRIGHT
(c) 2018-2021 L.Pinne, Germany.
.br
cs_show_hana_info comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
