.TH cs_show_wwpn 8 "20 Feb 2019" "" "ClusterTools2"
.\"
.SH NAME
cs_show_wwpn \- TODO 
.\"
.SH SYNOPSIS
.B cs_show_wwpn  \fI[OPTION]\fR
.\"
.SH DESCRIPTION
\fBcs_show_wwpn\fP 
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help.
.HP
\fB --version\fR
	show version.
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/cs_show_wwpn
	the program itself.
.TP
/etc/ClusterTools2/cs_show_wwpn
	the program's configuration.
.TP
/sys/class/fc_host/
	the TODO
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
https://build.opensuse.org/package/show?package=ClusterTools2&project=home%3Afmherschel
.\"
.SH SEE ALSO
\fBmultipath\fP(8)
.\"
.\"
.SH COPYRIGHT
(c) 2013-2019 L.Pinne, Germany.
.br
cs_show_wwpn comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
