.TH cs_show_cluster_patterns 8 "01 Nov 2019" "" "ClusterTools2"
.\"
.SH NAME
cs_show_cluster_patterns \- search log files for cluster patterns
.\"
.SH SYNOPSIS
.B cs_show_cluster_patterns \fIOPTION\fR
.\"
.SH DESCRIPTION
\fBcs_show_cluster_patterns\fP searches log files for cluster patterns.
Please note that most cluster components do logging to their local node only.
.br
.\"
.SH OPTIONS
.HP
\fB --help\fR
        show help.
.HP
\fB --version\fR
        show version.
.HP
\fB --writecfg\fR
	show some internal variables.
.HP
\fB --show\fR
        show all patterns.
.HP
\fB --fencing\fR
        show fencing patterns.
.HP
\fB --migration\fR
        show migration patterns.
.HP
\fB --count\fR
        count total for each pattern.
.HP
\fB --zip\fR
        count from compressed logs, too. This could take some time.
.HP
.\"
.SH EXAMPLES
.TP
* show migrations
.br
# cs_show_cluster_patterns -m
.TP
# cs_show_cluster_patterns -c | grep -v "=.0$"
count occurance of patterns, show non-null only
.TP
# cs_show_cluster_patterns -s | grep "^Jan"
show whole lines, but only for January. Useful if logs contain December as well.
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/cs_show_cluster_patterns
	the program itself.
.TP
/etc/ClusterTools2/cs_show_cluster_patterns
	the configuration.
.TP
/etc/corosync/corosync.conf
	the corosync configuration, maybe defining log file. 
.TP
/var/log/messages
	the default log file.
.\"
.SH BUGS
This script depends on LC_MESSAGES respective RC_LANG set to en_US or C.
Furthermore the scripts sort output by month. This results in wrong order of lines, if a logfile
f.e. contains December and January.
.br
Feedback is welcome, please mail to feedback@suse.com
.\"
.SH SEE ALSO
\fBcs_show_error_patterns\fP(8), \fBcs_show_cluster_transition\fP(8),
\fBgrep\fP(1), \fBsyslog\fP(8), \fBlogrotate\fP(8), \fBcorosync.conf\fP(5),
\fBClusterTools2\fP(7)
.\"
.SH COPYRIGHT
(c) 2011-2019 L.Pinne, Germany.
.br
cs_show_cluster_patterns comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
