.TH ClusterService 8 "10 Oct 2010" "" "ClusterTools2"
.\"
.SH NAME
ClusterService \- managing pacemaker high-availability cluster
.\"
.SH SYNOPSIS
.B ClusterService
.B cs_service
[\fIOPTION\fR] [\fIPARAMETER\fR]
.\"
.SH DESCRIPTION
Main command for managing a running cluster is \fBClusterService\fP.
This ASCII-terminal based menu system allows to perform common administrative
tasks. It can be used instead of hb_gui if no X desktop is available.
The program is a frontend to a set of tools.
.\"
.SH OPTIONS

\fB--rscFile\fR <resource file>
./ TODO: decribe files for wow functions and possible overwrites. 

.\"
.SH EXIT STATUS
.B 0
	Successful program execution.
.br
.B >0 
	Usage, syntax or execution errors.
.\"
.\" .SH EXAMPLES
.\"
.SH FILES
.TP
/usr/sbin/ClusterService
	the program itself.
.TP
/usr/share/ClusterTools2/ClusterService.rsc
	default ClusterService resource file.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
https://build.opensuse.org/package/show?package=ClusterTools2&project=home%3Afmherschel
.\"
.SH SEE ALSO
\fBClusterTools2\fP(7), \fBmenueng2\fP(7), \fBmenueng2\fP(8) 
.br
http://www.novell.com/saptechdocs/, http://www.novell.com/documentation/sle_ha/
.\"
.SH AUTHORS
Fabian Herschel
.\"
.SH COPYRIGHT
(c) 2009-2010 Fabian Herschel, Germany.
.br
ClusterService comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
