.TH cs_detect_sleha 8 "02 Aug 2016" "" "ClusterTools2"
.\"
.SH NAME
cs_detect_sleha \- looks for indicators of SLE-HA add-on
.\"
.SH SYNOPSIS
.B cs_detect_sleha
.br
.B cs_detect_sleha \fI[OPTION]\fR
.\"
.SH DESCRIPTION
\fBcs_detect_sleha\fP looks for RPMs, files, and repositories which might indicate an installation of the SLE-HA add-on.
.br
Un-installating all RPMs of SLE-HA is another function. Nevertheless, RPMs which were installed by dependency may remain on the system. Finally the script can remove almost all files and detach zypper repos which are related to SLE-HA.
.br
When detecting or removing SLE-HA, it is good to know that some RPMs are delivered with other products as well. F.e. libgnutls-extra26 with SLES, lighttpd and rubygems with SLE-SDK.
.\"
.SH OPTIONS
.HP
\fB --help\fR
	show help.
.HP
\fB --version\fR
	show version.
.HP
\fB --detect\fR
	shown number of traces, return code will also be that number.
.HP
\fB --installed\fR
	show installed base RPMs.
.HP
\fB --available\fR
	show available base RPMs.
.HP
\fB --standalone\fR
	show installed standalone RPMs.
.HP
\fB --files\fR
	show common files.
.HP
\fB --pedantic\fR
	show even minimal traces of SLE-HA.
.HP
\fB --removeall\fR
	remove RPMs, files, and repos of SLE-HA, as opposite to renewal.
.HP
\fB --uninstall\fR
	uninstall substantial RPMs of SLE-HA.
.HP
\fB --writecfg\fR
	show internal variables, f.e. lists of RPMs and files.
.\"
.SH EXAMPLES
.br
.TP
* Search for files and RPMs that might indicate components of SLE-HA are installed. Be pedantic with the search, but just print number of findings. A return code of "0" means "search went well, no traces of SLE-HA found". Return codes below "5" indicate some spoor, but usually not a functional SLE-HA installation. 
# \fBcs_detect_sleha 2>/dev/null; echo $?\fR
.TP
* Search for files and RPMs that might indicate components of SLE-HA are installed. Be pedantic with the search and print all findings. This might help, if the above search returned something obscure.
# \fBcs_detect_sleha --pedantic\fR
.TP
* Search for components that might run without SLE-HA, but are supported only together with SLE-HA - f.e. DRBD, OCFS2, ReaR. This might help, if a few hints were detected.
# \fBcs_detect_sleha -s\fR
.TP
* Search for config and status files. This might help finding out whether SLE-HA was in use. 
# \fBcs_detect_sleha -f\fR
.TP
* Uninstall substantial RPMs of SLE-HA. Some RPMs that are fetched as dependecy during installation will remain on the system. Also all files that are not handled by the RPM post-scripts will remain.
# \fBcs_detect_sleha --uninstall\fR
.TP
* Show what RPMs and files are known to this script. The output might be used for preparing a custom config file /etc/ClusterTools2/cs_detect_sleha.
# \fBcs_detect_sleha -w\fR
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.br
When called without any option, or with option "--detect", the return
code equals the number of indications found.
.br
0     : no SLE-HA
.br
<5    : some spoor, but no functional SLE-HA
.br
<10   : maybe standalone function installed (f.e. DRBD, OCFS2, ReaR)
.br
10-90 : maybe functional SLE-HA installed
.br
90>   : certainly functional SLE-HA installed, maybe used
.br
99>   : certainly functional SLE-HA installed and used
.\"
.SH FILES
.TP
/usr/sbin/cs_detect_sleha
        the program itself.
.TP
/etc/ClusterTools2/cs_detect_sleha, /usr/ClusterTools2/cs_delcib
        the configuration.
.\"
.SH BUGS
The "--removeall" function might damage the system - use it with caution. 
Detaching repositories from zypper is currently not implemented.
Feedback is welcome, please use the project page at
.br
https://build.opensuse.org/package/show?package=ClusterTools2&project=home%3Afmherschel
.\"
.SH SEE ALSO
\fBzypper\fP(8), \fBcs_delcib\fP(8), 
.\"
.SH COPYRIGHT
(c) 2016 L.Pinne, Germany.
.br
cs_detect_sleha comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
