.TH cs_man2pdf 8 "01 Feb 2016" "" "ClusterTools2"
.\"
.SH NAME
cs_man2pdf \- create PDF file from manual page
.\"
.SH SYNOPSIS
.B cs_man2pdf --help \fP|\fB --version
.br
.B cs_man2pdf --rpm \fI<rpm>\fR
.br
.B cs_man2pdf \fI<man_page> <section>\fR
.br
.\"
.SH DESCRIPTION
\fBcs_man2pdf\fP creates a PDF file from an manual page.
.br
Basically the command "man -Tps ... | ps2pdf - >..." is used.
The resulting PDFs could be read with any PDF viewer on eBook devices,
smartphones, or gaming consoles. 
.br
.\"
.SH OPTIONS
.HP
\fB --help\fR
        show help.
.HP
\fB --version\fR
        show version.
.HP
\fB --rpm \fI<rpm>\fR
        convert man pages from RPM.
.\"
.SH EXAMPLES
.TP
* create PDF for manual page sbd(7) and write the output into a file in the current working directory.
.br
# cs_man2pdf sbd 7
.TP
* create PDF files for manual pages of OCF resource agents.
.br
# apropos ocf_ | awk '$2~/7/ {print $1,"7"}' |\\
.br
  while read; do cs_man2pdf $REPLY; done
.TP
* create PDF files for manual pages in diretory ./mandir.
.br
# cs_man2pdf -d mandir
.TP
* create PDF files for manual pages from installed RPM ClusterTools2-doc.
.br
# cs_man2pdf -r ClusterTools2-doc 
.\"
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/cs_man2pdf
	the program itself.
.TP
$PWD/<man_page>.<n>.pdf
	the output file.
.\"
.SH BUGS
This script can only handle manual pages that with one single dot in the filename.
Feedback is welcome, please use the project page at
.br
https://build.opensuse.org/package/show?package=ClusterTools2&project=home%3Afmherschel
.\"
.SH SEE ALSO
\fBman\fP(1), \fBapropos\fP(1), \fBwhatis\fP(1), \fBmandb\fP(8), \fBps2pdf\fP(1)
.\"
.SH COPYRIGHT
(c) 2016 L.Pinne, Germany.
.br
cs_man2pdf comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
