.TH meminfolog 8 "21 Oct 2011" "" "ClusterTools2"
.\"
.SH NAME
meminfolog \- log the meminfo with timestamp
.\"
.SH SYNOPSIS
.B meminfolog \fI[ logfile ]\fR
.\"
.SH DESCRIPTION
\fBmeminfolog\fP logs the meminfo with timestamp.
Basically the script puts the output of "date +%F %T" in front of each line for the output of "cat /proc/meminfo".
.br
.\"
.SH EXAMPLES
.TP
To run meminfolog every 10 minutes, the crontab entry could look like this:
.br
-01-56/10 * * * * root /usr/sbin/meminfolog /var/log/meminfo.log
.TP
To rotate and compress the log from time to time, the logrotate entry could look like this:
.br
/var/log/meminfo.log {
    compress
    dateext
    maxage 365
    rotate 99
    size +2M
    notifempty
    missingok
    copytruncate
.br
}
.\"
.SH EXIT STATUS
.B 0
Successful program execution.
.br
.B >0 
Usage, syntax or execution errors.
.\"
.SH FILES
.TP
/usr/sbin/meminfolog
	the script itself.
.TP
/var/log/meminfo.log
	the default logfile.
.TP
/etc/cron.d/ClusterTools2
	the cron entry.
.TP
/etc/logrotate.d/ClusterTools2
	the logrotate entry.
.\"
.SH BUGS
Feedback is welcome, please use the project page at
.br
https://build.opensuse.org/package/show?package=ClusterTools2&project=home%3Afmherschel
.\"
.SH SEE ALSO
\fBproc\fP(5), \fBvmstat\fP(8), \fBcrontab\fP(5), \fBlogrotate\fP(8), \fBClusterTools2\fP(7)
.\"
.SH COPYRIGHT
(c) 2011 L.Pinne, Germany.
.br
meminfolog comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
